### ISSUE TITLE
On data index, add data explorer indicator links

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#10]

**Comment by cgettings** [comment]
In cases where there are 2+ subtopics, the link goes to the indicator page for the first subtopic.

**Comment by mmontesanonyc** [comment]
Can you show me what this does? I don't quite follow.

**Comment by cgettings** [comment]
![image](https://user-images.githubusercontent.com/12686912/181254822-f426ea55-6d0d-4a9a-afaf-d7240d5ffcb0.png)

The `subtopics[0].subtopic` bit uses the first subtopic. So if Court-Ordered Evictions is listed in the frontmatter of both _Housing_ and _Social and Economic Conditions_, the indicator will link to `?id=<IndicatorID>` under `housing`, so, `data-explorer/housing/?id=<IndicatorID>`.

**Comment by mmontesanonyc** [comment]
Ah ha. Nice. Thanks!
