### ISSUE TITLE
Incorporate dohmh health topics as links from DE pages

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#1000]
For each Data Explorer topic:
- [x] Get corresponding link from [Health Topics A to Z](https://www.nyc.gov/site/doh/health/health-topics.page)
- [x] Put it in frontmatter

Then create a template item that provides a link to More Resources (possibly among Take Action / 311 / Share - maybe called Protect Your Health?).

**Comment by mmontesanonyc** [comment]
@etorem - before we merge, I added a bit to pipe this in at the end of the About Text. Can you please take a look though? Does this work?

**Comment by etorem** [comment]
@mmontesanonyc 
I think this works! You had mentioned saying Protect your health before -- but I think this is more generic given the wide variety of resources we will be sharing.

**Comment by mmontesanonyc** [comment]
Thanks!
Yeah, any time we put a title into a sentence there's the challenge of dealing with the wide variety of topics we have; if our portal was only various health outcomes, for example, it would be more straightforward. 

I had originally thought of this being closer to the Take Action stuff but I think it works as a companion to .Content. 

One other thing for you to consider broadly as you think through extant content - are there areas where we can pull other links from DE pages' .Content section and instead just leverage a central/core link to A-Z?

**Comment by mmontesanonyc** [comment]
Closing as completed.
