### ISSUE TITLE
Create interpretive sentences

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#106]
How do I read this chart?

**Comment by mmontesanonyc** [comment]
What are you thinking for this?

One idea I have is, a light button on each view - clicking it fires a modal that delivers a couple paragraphs specific to the view - summary, map, trend, and links.

**Comment by cgettings** [comment]
I’m envisioning something that gives an example of an interpretation, using MeasureName and maybe even a specific neighborhood from the chart. Like for links: “A neighborhood under the the line….” Will have to be careful about wording, but I think this could be really helpful.

**Comment by mmontesanonyc** [comment]
Ah - I like the sound of that a lot. Putting data into sentence form has the potential to really support people's understanding/interpretation of the data.

There are different implementations we can do for the different views. For example, say, for Evictions, we could do the following for both the summary table and the map:

_In NYC, there were **3026** evictions in 2020, or **8.6 per 10,000 homes**, ranging from 1.61 per 10,000 homes in the Upper West Side to 28.84 in Morrisania/East Tremont._

The JS would just have to parse the data object, identify the NYC value, and the largest and smallest values of the geo of interest, and pipe that into text. 

---
Trend might be tricky - I'm not entirely sure what to do here. We could always compare citywide values from the most recent year to the first, but that has the potential to be kind of wack - we could programmatically declare something rising or falling when really it's just stochastic and roughly flat.

I agree that the Links text would need careful wording. A few things we could do:
- calculate the R-squared (vega-lite can do this, but accessing it via page-level javascript might be a challenge)
- create thresholds for weak, moderate, and strong relationships

**Comment by mmontesanonyc** [comment]
I'm going to close this as inactive right now. It's in the "Data Explorer Enhancements" bit in our project board and document, and I want to keep the Issues list focused on active things.
