### ISSUE TITLE
Improve trend charts

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#1127]
Hey folks, I've been mulling over the trend charts for a while and want to brainstorm ways to improve them. There are a few challenges:

Legends/labelling. We chose to go for legends instead of the usually-preferred labels (or label-final) because we have a lot of closely-clustered data that results in overlapping labels at the final value. Legends have their own challenges, especially on mobile display, so we wind up calculating a number of columns for the legend, based on screen width, and passing that into the spec.

Tooltip. I liked the approach we chose at the time, but now I think it's overwrought and doesn't adequately identify one series. If we had highlight-one-line-on-hover, then we might not need the legend - or could greatly de-emphasize it. 

A few standard approaches: 
- [label temporal values](https://vega.github.io/vega-lite/examples/interactive_multi_line_label.html), which we could modify to have the [series name in the tooltip, too](https://vega.github.io/editor/#/gist/0bc11005c73cbc61f612c2bb6a986217/spec.json) (though this approach is good for hovering but maybe not great on mobile?)
- [hover-highlight](https://vega.github.io/vega-lite/examples/interactive_line_hover.html);  

I think my ideal approach would be something that:
- Doesn't require a legend
- Works well on mobile (eg tap instead of hover)
- Aids individual series identification

@cgettings, @etorem what do you think?

**Comment by mmontesanonyc** [comment]
I have a spec [here](https://vega.github.io/editor/#/gist/60baa87fd259367dd6a1af2e0502cc94/spec.json) that is pretty different from the existing spec:
- Simplified
- Uses single-series tooltips at point
- Includes a line hover feature
- Also uses the viridis-esque colors we've been talking about

A few things I'd like to add to this:

A **strokeWidth or opacity conditional** that gives more weight to New York City. But every time I add a strokeWidth condition test, it doesn't work as expected. @cgettings I know your time is precious this month, but if you have a few minutes I'd love to see what you make of it. i would expect the below to work in a number of places but it does not. 

```
    "strokeWidth": {
      "condition": {"test": "datum.properties.Geography === 'New York City'", "value": 5}, 
      "value": 3
    },
```


**Label final value on hover**. Adding the below gets us part of the way there, but not quite. (Shelving this until we figure out [the x-axis thing](https://github.com/nychealth/EH-dataportal/issues/1080), and picking up from there, might let us use `end_period` which can probably aggregate in a way that `TimePeriod` can't.)

```
    {
      "encoding": {
        "x": {"aggregate": "max", "field": "TimePeriod"},
        "y": {"aggregate": {"argmax": "TimePeriod"}, "field": "Value"}
      },
      "layer": [
        {
          "mark": {"type": "text", "align": "left", "dx": 4},
          "encoding": {
            "text": {
              "condition": {"param": "hover", "field": "Geography"},
              "value": ""
            }
          }
        }
      ]
    }
```

**Comment by mmontesanonyc** [comment]
In [this](https://vega.github.io/editor/#/gist/d023a379d9e76da8cebaca07a5b97d22/spec.json) I've incorporated our new approaches for x-axis labelling and scaling. I also got a start on label-final-value, but despite what the code is telling me, it's labelling every value and not triggering on hover.

**Comment by mmontesanonyc** [comment]
[Updated spec](https://vega.github.io/editor/#/gist/d33cfa8b35c822102202c7375da5ac95/spec.json) with the hover working as intended. Thoughts on this as a replacement? I might need to back this in to `comparisons.js` to test it out with a variety of datasets for us to properly evaluate. @cgettings @etorem 

May be easier to do left-side labels without overlap or padding issues.
One issue re: using this approach is the lack of legend for screenshot/re-use purposes.

**Comment by etorem** [comment]
<img width="733" alt="Screenshot 2024-09-12 at 9 34 08 AM" src="https://github.com/user-attachments/assets/f621dc47-ae6e-4f2d-8aab-4563b6263405">
I think I like it with a slightly thinner line, like this (line 664, strokeWidth: 3). Or 3.5. What do you think? @mmontesanonyc 

I think it looks great, I'm glad we can display single borough values now and the palette is really nice.

**Comment by mmontesanonyc** [comment]
@etorem agreed! thinned. I also revised dimensions, changed "For" to "Group" and did a little management of the x-axis labels as they respond to width. A bit of "manual responsiveness" built in. 

I'm going to let this marinate for a bit.

Semi-related - since this work is taking place on a branch initially about reviewing colors - @cgettings and I talked about using viridis for the maps. I speculate that the colors don't have built-in judgement and we may not need to have the red and blue alternates. Will make for an interesting conversation.

**Comment by mmontesanonyc** [comment]
A few issues:
- [ ] AQ action days and ozone actions days don't have the right info in their tooltip prompt, which may be a metadata-grammer issue
- [x] Difficulty selecting on mobile - add legend on mobile?
- [x] Hover is sometimes causing the title and subtitle to move to the left (!)
- [ ] Possible layered labels. 

Add to color, on mobile:
```
        "legend": {
          "orient": "bottom",
          "columns": 3
        }
```

**Comment by mmontesanonyc** [comment]
@cgettings this is exposing a metadata-grammar problem that we have on AQ Action Days (3 indicators: 92, 57, 55). I feel like how `measure name`, `measurement type`, and `display type` are handled on these are out of sync with the rest of our indicators and are leading to this issue.  

![image](https://github.com/user-attachments/assets/2e0c3fd9-18ad-4051-8616-8d2d210093d4)
