### ISSUE TITLE
Data Explorer enhancements

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#13]
A bunch of things to look into, here:

**Topic selection**
Data Explorer landing page could communicate more information. And, on topic pages, we currently have a search bar in the sub nav. We could revise this to a "change topic" button that launches a modal (and matches the "change dataset" button which could help communicate topic/dataset hierarchy organization), and have it launch a modal (a partial?) that's the same as what's on the DE landing page, for consistency.

For the chooser itself, maybe we organize topic by Key Topic to help organize info, and also offer a preview of what indicators each topic has - so users can make an informed choice.

**Data Explorer page components**
- Revise arrangement of page components (maybe the copy citation should be on the same row as download data?)
- Currently, the About text is hidden on XS screens. When that happens, consider an "About this topic" link that launches a modal with {{ .Content }} in it. 
- We should consider re-sizing all of the charts - they all feel just a hair too large for the page.
- Styles: We should consider a light gray background, with content blocks in white panels 'above' the page. I'm not sure if this has implications for the whole dang site. 
- We'll need a strategy for the Links spec - too many geographies for the legend. We could either hide the legend, or look into coloring the bubbles by borough.

**Comment by mmontesanonyc** [comment]
I re-build the data explorer chooser, putting it into a partial `de-chooser.html` so we can call it into a modal in other places.

However, there's a preview function I'd like to build in, and I'm not 100% sure how it should look or work - but basically on hovering over a topic link, I'd like to list the indicators (somewhere - maybe a third column? or maybe underneath?)

I'm not 100% sure how to do this but I think it's:
- range through DE topic pages to get indicator IDs
- then loop thru indicators.json to get the indicator name for each ID
- then print them to the preview div

![image](https://user-images.githubusercontent.com/55593359/181601620-f36356ab-bb5f-4a7b-8fb9-07e6d2aed926.png)

**Comment by cgettings** [comment]
Re: how to do it, that sounds very similar to how the Data Index works

**Comment by cgettings** [comment]
> * We'll need a strategy for the Links spec - too many geographies for the legend. We could either hide the legend, or look into coloring the bubbles by borough.

I like this idea.

**Comment by mmontesanonyc** [comment]
Thanks for the reminder about `subtopic_indicators.json`! That's a really helpful file to have. 

I built the data explorer chooser into a modal on the data explorer, but it will require re-factoring the Hugo code on `de-choser.html` - it's set to look for regular pages under /data-explorer so it trips when it's on a subpage. 
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/55593359/181768523-40cbbcdc-4dbe-4c42-9c11-0fe8ce658993.png">

Those badges might need a label - they show how many subtopics are within. Needs some refinement but I think this is heading in the right direction.
<img width="827" alt="image" src="https://user-images.githubusercontent.com/55593359/181768795-8d7a7a6f-14bf-4a59-ab7f-bac6dacaaed1.png">

**Comment by mmontesanonyc** [comment]
Two issues so far:
- First, I haven't fully wrapped my head around either the design or implementation of previewing what indicators are within what topics. Might need your help on implementation, @cgettings, and we can probably brainstorm how it looks/feels.
- Second, I like the idea of having the data explorer topic-selector be modular. Currently, it's a partial called `de-chooser.html`, and I prototyped a "Change topic" button that launches a modal with the `de-chooser` partial inside of it. But, it comes up empty, and I'm not sure how to fix it. So, that's commented out for now.

However, also want to point out a bunch of small design changes I made to the DE itself. Adding a bunch of little labels with this `sm-label` class to help organize pieces of information. I also piped in the indicator name above each visualization, for screenshottability.
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/55593359/183083237-0f245d5f-73d6-4309-8227-1480623eb8c3.png">

And, I organized a bunch of stuff below. Different color buttons to distinguish from the main DE interaction buttons. The "this view" option under Download Data is not functional yet - may need you, @cgettings, to help out with that too. 
<img width="941" alt="image" src="https://user-images.githubusercontent.com/55593359/183083658-5a41f3a0-e431-489f-8494-ee50b06431d8.png">

**Comment by mmontesanonyc** [comment]
Several enhancements merged in:
- [Layout (field labels, visualization titles)](https://github.com/nychealth/EH-dataportal/pull/70)
- [Citation button, download feature, and other footer items](https://github.com/nychealth/EH-dataportal/pull/68)
- [DE landing page chooser, plus DE 'change topic' chooser modal](https://github.com/nychealth/EH-dataportal/pull/67)

Safe to close this general issue.
