### ISSUE TITLE
Enhance mobile styling and layouts

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#151]
We've done some work on this, but we need a more systematic effort.

**Comment by mmontesanonyc** [comment]
There are a few places in particular I think we can make gains:
- [ ] DE - Topic About Box should be hidden on mobile (mobile view reveals an About Topic button to launch a modal)
- [ ] DE - visualization views have legends on the right hand size, which eats into the vis a lot. I wonder if it's possible to set mobile and desktop views, mobile with the legend above. Might want a smaller height for the vis container on mobile, too?
- [x] Landing pages - we have too-tight columns on the DE landing page, for example - we can just class a lot of elements with `col-sm-12`

I think a lot of stuff is probably just a matter of assembling a bunch of things we can hotfix in one fell swoop; the visualization on mobile is another thing. I wonder if we could use `screen.width` ([doc](https://www.w3schools.com/jsref/prop_screen_width.asp)) to add a little function that sets the legend orientation from `right` to `top` based on the screen width.

**Comment by mmontesanonyc** [comment]
Bunch of issues:

Home page - these need some spacing between them (probably a `mb-1` class applied).
<img width="326" alt="image" src="https://user-images.githubusercontent.com/55593359/192774886-6104a000-068c-4639-8b9b-f6c7406d2b9f.png">

Data Explorer - these need `col-sm-12` applied:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/55593359/192774767-a92245f1-813f-4e84-ab5c-919cce11d917.png">

Data Explorer - hiding About box - I forget the class that this needs off hand.
<img width="326" alt="image" src="https://user-images.githubusercontent.com/55593359/192775122-c61b5288-5e2e-446c-afa7-11797d1226d5.png">

Data Explorer - vis dimensions:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/55593359/192775262-ce5dac36-672e-49aa-81d3-79ec634fe07f.png">

**Comment by mmontesanonyc** [comment]
I'm experimenting with using `window.innerWidth` to determine different values for legend orientation and vis height, but I'm still running into a couple width issues - I'll keep tinkering though. 

<img width="306" alt="image" src="https://user-images.githubusercontent.com/55593359/193342002-9b3e307e-034f-47bb-a860-b7f4eb6f8e9f.png">

**Comment by mmontesanonyc** [comment]
Ah ha - adding `config.legend.columns = 3` lets you set columns in the legend. I had it in a different spot.
Additionally, I replaced the height and the legend orientation with variables, and added this:
```
        // get dimensions
        var legendOrientation;
        var visHeight = 500;
        window.innerWidth < 576 ? legendOrientation = "top" : "right"
        window.innerWidth < 576 ? visHeight = 300 : 500;
```
Which is pretty straightforward, but even better would be adding an event listener on `window.resize` to re-establish the variables and re-draw the chart. 

We'll also have to get into the height for the parent divs for the charts, since those have heights coded into the template. Would be good to put that somewhere else. Overall: progress!

<img width="306" alt="image" src="https://user-images.githubusercontent.com/55593359/193343611-2bcb1ddb-9e0e-419a-937f-09e876762f94.png">

**Comment by mmontesanonyc** [comment]
Having a responsive height using `height:50vmin` on the visualization container gives some nice dimensions that flow well.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/55593359/194358733-bc541a9f-4d3a-475c-a20e-849dbe14fd97.png">

![image](https://user-images.githubusercontent.com/55593359/194358971-3b910198-85f3-41f4-b69e-070520b89d66.png)

On this second image there's also `overflow-fade` applied two the two sidebar boxes, which works really well as a prompt to scroll - nice idea, @cgettings.

I'm refining a bunch of dimensions and layout of small items, simplifying a bit and getting things tidier on both desktop and mobile. This is all happening in a dummy template file; it might take some work to re-integrate, but will be worth it.

**Comment by mmontesanonyc** [comment]
Work focusing on #158
