### ISSUE TITLE
Add flag to pages if they're displaying staged data

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#167]
Add based on hugo environment variables, that reflect our data pipelines - flag that tells us if page is showing data from the staging branch.

**Comment by mmontesanonyc** [comment]
Hey @cgettings per our chat earlier, I thought that staging was showing production data, but in `config/staging/config.toml` has `data_branch = staging`. So - were we wrong this morning?

**Comment by cgettings** [comment]
Our current situation is confusing, owing to that site/data combo issue. The only difference between the two environments is the data branch, and I’ve set up the gh-p build to use the “prod” environment. 

Alternatively, we could specify the “prod” data branch in the staging config, then build gh-p with the staging environment. 

Another thing could be triggering a prod site / staging data build on merge to prod, using a 3rd config/environment. Then we’d get a deploy build (prod/prod), and a data preview build (prod/staging).

**Comment by mmontesanonyc** [comment]
Ah so staging serves staging, but when staging is built to gh-p, it builds using production data. 

I feel like we're still ironing our our environments, but maybe we should consider a location on an internal server (i deployed a thing to 201) to be a pre-prod build with staging data. That accomplishes a couple things: an internal review of staged data (for us, and for partners), and a near-prod mirror site. This lets us still use `staging` as, well, development (maybe we should change the name...).

**Comment by cgettings** [comment]
Yeah, I realize now that `staging` is actually _`development`_, and my new branch `data-staging` is actually _`staging`_. Maybe let's change the names.

**Comment by cgettings** [comment]
@mmontesanonyc Ok, so: `staging` is now `development`, `prod` is now `production`, `deploy` is now `prod-deploy`, and `data-staging` is the same. Make sense?

**ETA:** Here's some code that will save you some trouble:

```
git fetch

# rename
git branch -m staging development

# reset tracking branch
git branch development -u origin/development

git branch -m prod production
git branch production -u origin/production

git branch -m deploy prod-deploy
git branch prod-deploy -u origin/prod-deploy

# reset local list of remote branches
git prune
```

_et voilà!_

**Comment by mmontesanonyc** [comment]
Cool, I merged the environment changes back into `hotfix-add-env-flag` to test - can you doublecheck to make sure all's working as expected, and then merge on in? Thx.
