### ISSUE TITLE
Create multiple measure Trend displays

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#190]
For some measures, the Trend chart shouldn't display geographies, but rather multiple measures. A list (hopefully complete) of Indicators/measures for which this is the case is below.

To implement, we can add info to `indicators.json` - at the measure level in that file, there is `visOptions.Trend` component, which looks like this:
```
            "Trend":[
              {
                "On":0,
                "Disparities":0
              }
            ],

```
...and could be revised/enhanced to look something like this:

```
            "Trend":[
              {
                "On":0,
                "Disparities":0,
                "multipleMeasures": [XXXX,YYYY,ZZZZ],
              }
            ],

```
Then, when that measure is being displayed, the front-end code can look for the presence of `multipleMeasures` and use a different Trend code that ingests the additionally listed measures and sends them to another trend spec. We can refine specifics later.

**Multiple-measure displays** - I'm not sure if this is comprehensive - if we're able to crossreference from a database location, that would be helpful. 

---
_AQ: Citywide regulatory monitoring:_
AQ Advisory Days - sensitive groups, general population
Ozone - Days above reg standard; sensitive groups

_Asthma_
ED Visits (adults): Children 0 to 4, Children 5 to 17.

_Pesticides_
Agency use of BPs - All agency solids, DOE solids, NYCHA solids
Agency use of Fungicides - all agency, parks golf, parks no golf 
Agency use of Herbicides - all agency, parks golf, parks no golf 
Agency use of insecticides - All agency solids, DOE solids, NYCHA solids
Agency use of rodenticides - all agency solids, DOHMH solids, DOE solids

_DWQ_
Arsenic: annual average, MCL, maximum
HAA5: MCL, quarterly average, max
TTHM: MCL, max, annual average
Nitrate: MCL, max, annual average

_Carbon monoxide:_
deaths: fire related, non-fire-related, unknown cause
hosps: fire, non-fire, overall

_Obesity_
Obese adults: obese youth

_Weather-related illness_
heat stress deaths: heat events, heat stress deaths

_Worker health_
Worker deaths in construction industry: NYC, USA

---

**Comment by cgettings** [comment]
Three potential ways the trend chart display can be configured for an indicator:
1. Boro-only comparison 
   - when we only want to compare boros [_current_]
2. Multiple measures comparison only 
    - when we want to compare multiple measures, but only have city-level data
3. Both boro & multiple
    - when we want to compare multiple measures, and have boro-level data
 
To decide (2) vs. (3), either the front end needs to check the available geos, or indicators.json needs to include every potential comparison type, instead of just defaulting to boro when nothing is specified.

**Comment by mmontesanonyc** [comment]
Hmm. Do we have any instances of 3? I just ran a check, and didn't see any on the old portal - but also, I found that asthma and obesity weren't displaying multiple-measure displays (though I had listed them, above - perhaps things changed?).

**Comment by cgettings** [comment]
At least 1:
[Asthma Hospitalizations (Adults): Boro](https://a816-dohbesp.nyc.gov/IndicatorPublic/VisualizationData.aspx?id=2382,4466a0,11,ChartOverTime,Boroughs,Estimated%20Annual%20Rate)
[Asthma Hospitalizations (Adults): Age](https://a816-dohbesp.nyc.gov/IndicatorPublic/VisualizationData.aspx?id=2382,4466a0,11,ChartOverTime,Age,Estimated%20Annual%20Rate)

**Comment by mmontesanonyc** [comment]
Ah. Well at least it's not a display of both boros and multiple measures at the same time!

So the options button allows us to see either default (single measure, by boros) or "by age" which is effectively multiple measures. I'm not crazy about that pattern there - it really feels like a hack, and replicating it seems like it could be a problem since we are considering adding "age" as a data facet, instead of how we have it now, as a separate indicator.  [Obesity has this too](https://a816-dohbesp.nyc.gov/IndicatorPublic/VisualizationData.aspx?id=2063,4466a0,113,ChartOverTime,Boroughs,Percent). 

OK, so two questions here. One is the interaction pattern, and the other is the logic.

For the interaction pattern, I could imagine a button or switch with "Show boros / Show comparisons" option (might be nice to not have this be a dropdown). That is: the chart loads by default showing boroughs, but if multipleMeasures exists, then there's a button labeled "Show Comparisons". When you click it, the chart shows the multipleMeasure comparisons (and the button changes to say Show Boroughs). 

Logic: I think indicators.json including every potential comparison type seems like a drag. What if we go with your proposed logic: defaulting to boro when nothing is specified. If something _is_ specified, maybe we default to the multipleMeasure display; then, if boros exist, show but toggle button to toggle? 

I'm not 100% sure this covers data types here, though.

**Comment by cgettings** [comment]
I like that idea.

**Comment by mmontesanonyc** [comment]
[Here's a checkbox toggler we can use](https://jsfiddle.net/mmontesano/sg7n1jm5/2/). 

re: the logic, I'm going to do another survey of portal indicators to check this logic against instances of multiple Measures. The list I have above might not be complete - do you know where multiple Measures are set in the database (measure-to-measure table?)? Would be nice to programmatically generate a list of indicators, so we know we're not missing anything. 

But overall, I want to test this logic for each instance, to make sure that there's not another data type that needs to be considered - i want to ensure that this logic captures all the states.

**Comment by mmontesanonyc** [comment]
What needs to happen:
- [x] add files to onedrive
- [x] create comparison.json

Notes on Comparisons:
- We're operating based on clusters
- We have "within indicator" and "other indicator" versions - but that doesn't really matter
- We have some indicators with multiple clusters (HAA5, TTHMs, pesticides) - that's a little tricky
- New chart spec, because lines are labelled not by geography but by measure name. 
- Menu/toggler/option handling is a little tricky but logic is in place (?)

**Comment by mmontesanonyc** [comment]
[Set of togglers we can use](https://jsfiddle.net/mmontesano/wx512r9v/8/).

**Comment by cgettings** [comment]
We could also use Bootstrap's [button group](https://getbootstrap.com/docs/4.0/components/button-group/).

**Comment by mmontesanonyc** [comment]
that might be simpler: use btn-outline-x for the inactive one, btn-x for the active one, have JS toggle those classes on selection:

![image](https://user-images.githubusercontent.com/55593359/207937579-e4c0d5b8-5937-4531-97a5-5207318165c4.png)

**Comment by mmontesanonyc** [comment]
Actually... that would let us turn the Comparison "on" switch into a dropdown for the instances where we have multiple comparison clusters (DWQ, pesticides).

![image](https://user-images.githubusercontent.com/55593359/207938055-a70888ca-2fee-41f2-b149-f23ed60a459f.png)

**Comment by mmontesanonyc** [comment]
Noting a few things from my review:
- Menu and Comparison functionality isn't quite there: in DWQ/Nitrate, I've got individual measures in the 'Comparisons' menu, instead of a comparison. in Carbon Monoxide ED visits, we've got a lot of extra stuff in the menu under Cause-Specific Comparison. 
- Given how this works we should probably change the menu name to Options, for both 'comparisons' and non-comparison indicators where we usually have a drop-down labelled Measure
- Related to the above, it might be nice for the selection to display as the button's innerHTML - but for comparisons we have some really long titles - so maybe not. 
- legend: let's make this one line unless mobile (let's ID instances where that doesn't work and think through it).
- Colors: dominant/secondary, where the 'host' measure is the dominant color. 

A few general chart notes, too, that can happen in this branch.
- let's apply `"interpolate": "monotone"` to the regular trend chart, too
- let's add `"tickCount": 4` to comparisons, trend, and links specs. this would go in `encoding.y.axis` and will slim down some of our runaway labels.

**Comment by cgettings** [comment]
Just need some cleanup and commenting and this will be ready for dev

**Comment by mmontesanonyc** [comment]
Great! I found one bug. We could go to dev with it and you could take a breather, knowing that there might be some additional work on it to come after WM and others see it - or you could tackle it now before going to dev. your call.

**Changing indicators**: if you are on an indicator with 'compare' and then click to a different indicator (go to Heat Events, click Trend, and then click Heat Vulnerability Index) that does not have a trend chart activated, the previous indicator's Trend/Compare chart persists. The 'Compare' menu remains but is unpopulated. So something is refreshing, but not everything. Recommendation: if going from T/C=yes to T/C=no, just default back to Summary table?

And a few small things:
- Default compare: we have both measures and comparisons for a lot of things. Possible to default to comparison, which is the most informative view?
- CO menu is a little out of control. I think this has to do with Comparisons.json (notice leading commas in ComparisonID 645, 646), and just text, rather than misfunctionality. Like, I think the ComparisonNames need to be: Fire-related (rate), non fire-related (rate), and all causes (rate) - and the same set but for number.
- Colors: Great job getting black as the primary indicator. Can we put a slight opacity on the other colors? Maybe 75%? To put them in the background just a bit. 

And a few things we should talk about:
- If there's only one item in the Compare menu, can/should we remove the button? 
- Re-name "Compare" to "Options"? In fact... right now we only have a single Options menu, but we call it Measure, Compare, or Links. While I'd like to expand this so that, say, Map has a menu system that works more like the Summary (Geography | Year), maybe we can take an interim step toward consistency and have the ones on Map, Trend, and Links just say Options. or Show: ?

**Comment by cgettings** [comment]
- [x] Possible to default to comparison, which is the most informative view?
- [x] Can we put a slight opacity on the other colors? Maybe 75%?

Talk about
- [ ] If there's only one item in the Compare menu, can/should we remove the button?
- [x] Re-name "Options" menus "Show:"

**Comment by cgettings** [comment]
Maybe we make the drop down inactive, sort of the same idea as the geo checks

**Comment by cgettings** [comment]
After updating the copy, here's what the comparisons chart looks like:

![Screenshot (17)](https://user-images.githubusercontent.com/12686912/221283219-62543e7f-530d-42d7-ab52-4867dadd91ea.png)

@mmontesanonyc @etorem

**Comment by mmontesanonyc** [comment]
Taking a look at #523 ...

That's looking great. I also like your revisions to the styles of the chart title, with the title a little larger than it was before. 

I'm finding a couple of things to keep wrangling on:

On CO ED visits we've got some conflicts between the spec and the labels, so we've got "per 100,000" three times on the chart. 

<img width="876" alt="image" src="https://user-images.githubusercontent.com/55593359/221284260-dc31cbb5-7163-4be8-95d7-aa67632565c6.png">

Heat event - does it make sense to create a new comparison that bundles 90, 95, and 100 degree days together into a new comparison bundle? And, can the other label be just "Heat events and heat stress deaths"? (not sure if this is a complicated field issue, or if this one just slipped thru the editing process)
<img width="876" alt="image" src="https://user-images.githubusercontent.com/55593359/221284720-4cef9178-56de-48cc-84f3-94cd2d757b57.png">

DWQ - nice job bringing in the 3-year filter! I was going to chat about this with you this week but it slipped off. Thanks for adding that to this bundle. But - seeing a character issue being piped in here. And, can we add the 3-year filter to TTHM in addition to HAA5? And can we also keep those charts the full width of the pane there? 
<img width="876" alt="image" src="https://user-images.githubusercontent.com/55593359/221285107-34c418e7-50ed-4410-b39e-2821e84e5a62.png">

**Comment by mmontesanonyc** [comment]
re: #523 

Looking great, plus good changes to the titles, and incorporating the 3-year filter for DWQ! Brief notes:

- ~~CO ED visits - (per 100,000) is 3x on the chart - may be both a copy and a logic issue.~~
- Heat events - can we make a new Comparison that has the 90, 95, and 100 degree days as a single bundle? 
- DWQ - 3-year - nice! Can we extend that to the full width of the chart? And, apply to both Disinfection Byproducts indicators.

**Comment by cgettings** [comment]
Didn’t actually do the 3 year filter yet. 

Re: copy stuff, all the changes are on the staging branch, so you might be seeing old copy unless you’re serving data_staging. 

![image](https://user-images.githubusercontent.com/12686912/221322513-16d49481-5e04-4dbc-b00f-4fa570b13fd7.png)

**Comment by mmontesanonyc** [comment]
Ah yes I was definitely not serving `data_staging`, thanks and sorry. The updated copy is looking great. Recommend we merge into `development` and then check in with KL to see if the climate team agrees about creating a new comparisons bundle on those temperature measures. 

re: 3-year - I saw the quarterly HAA5 chart and assumed it had a 3-year filter on it: `/data-explorer/drinking-water-quality/?id=2043#display=trend`. No priority right now then. 

Sorry for being all confused at the end of last week with this! More tk when we check in tomorrow.

**Comment by cgettings** [comment]
No worries. It is pretty confusing.

**Comment by mmontesanonyc** [comment]
👏 👏  👏
