### ISSUE TITLE
NRs: link to DE page (merge to prod)

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#193]

**Comment by mmontesanonyc** [comment]
@cgettings, could you please add this to your list for when we finish deployment?

The [report json's](https://raw.githubusercontent.com/nychealth/EHDP-data/production/neighborhood-reports/reports/Active%20Design%20Physical%20Activity%20and%20Health%20in%20Bayside%20-%20Little%20Neck.json) `indicator_URL` could be replaced with URLs on the current site, so we could add a button on the new site's NRs that link the user to `/data-explorer/TOPIC/?id=INDICATOR`.

**Comment by cgettings** [comment]
We should use subtopic_indicators.json thru Hugo, instead of trying to update the SQL server view, because that keeps the DE markdown as the canonical topic-indicator relationship definition.

**Comment by mmontesanonyc** [comment]
Good call, I like that. 
A little tricky since that assembles on build, and we don't build locally - but we can always reference [the file on](https://raw.githubusercontent.com/nychealth/EH-dataportal/prod-deploy/IndicatorData/subtopic_indicators.json) `prod-deploy` which would be the same as any actual deployed one. 

I think I can tackle this - I figure JS could loop through and just find the first instance of an IndicatorID, and then use its parent to assemble the link URL.

**Comment by cgettings** [comment]
Which is what we do on the data index!

**Comment by cgettings** [comment]
I'm just not sure when subtopic_indicators.json will be available - it gets built when you build or serve, so it will eventually be available, but not sure when in the pipeline.

One thing we could do is include the relevant Hugo code in an NR template, or even in head.html.

**Comment by cgettings** [comment]
The data explorer content is processed before the NR content (alphabetical), so subtopic_indicators.json will be available to the NR templates. It's not the most reliable thing, but it'll work.

**Comment by mmontesanonyc** [comment]
Functional! Each modal gets the Indicator ID from `indicator_URL` in the JSON spec. The value for this fiels is the oldportal URL:
`"indicator_URL":"http://a816-dohbesp.nyc.gov/IndicatorPublic/VisualizationData.aspx?id=2381,1,1,Summarize"`

We use Hugo to remove everything but the Indicator ID, and when you click on an indicator, it passes the indicator in to the function `getURL()`.  This is an async function that waits for `getJSON()` to finish first. 

It then looks through `subtopic_indicators.json` for the Indicator ID and returns the parent Topic, and then builds the URL: `/data-explorer/TOPIC/?id=INDICATOR-ID`.

---

BUT - relying on the oldportal URL in the json spec is a little clumsy. it would be a lot easier to plan to update this to just include the IndicatorID instead, at some point. That would require updating `report_indicator.html` to just use IndicatorID instead of producing it from the URL.

**Comment by mmontesanonyc** [comment]
@cgettings can you take a look?

One thing I'm concerned about is error handling. I know/think there are some indicators on NRs that are part of "other nyc data" and not in topics in the DE. I'm sure that there's a way to handle it, in getURL(), if the function doesn't find a parent topic for that indicator ID. But I'm not sure what we should _do_ in that instance - maybe hide the Get The Dataset button for that indicator?

**Comment by cgettings** [comment]
@mmontesanonyc I can update the SQL server view to include the IndicatorID instead of the URL. Should be a pretty simple to then update report_indicator.

Re: errors. I think hiding the button is a good idea.

**Comment by mmontesanonyc** [comment]
Thanks! OK, if you work on the spec, I'll work on error handling. Should be reasonably straightforward.

**Comment by mmontesanonyc** [comment]
Turns out that was simple - Psychological Distress, on the Climate report, doesn't have a subtopic. the if/else in getURL() provides a nice spot to hide the button. 

@cgettings, lmk when you update the json spec and we'll nudge this over the line.

**Comment by mmontesanonyc** [comment]
Check that - need to re-do my QC...

**Comment by cgettings** [comment]
@mmontesanonyc  JSON updated!

**Comment by mmontesanonyc** [comment]
NRs updates - this works on `hugo serve --environment production` - @cgettings, can you please merge the json+IndicatorID to the staging branch so that it will work on `serve --environment development` too?

**Comment by cgettings** [comment]
@mmontesanonyc done

**Comment by mmontesanonyc** [comment]
thanks! I'll let this breathe for a minute, and i'll plan to merge to development tomorrow morning, test a bit, and then get it going toward prod.

**Comment by mmontesanonyc** [comment]
Thanks for the tweak - found one more to tidy up.
Unfortunately I found this only works if I include `--ignoreCache`. I'll check on another machine shortly - but concerned that if we merge into `development` it also might not work there.

**Comment by mmontesanonyc** [comment]
Works on work machine - I'm going to merge to development to test that.

**Comment by mmontesanonyc** [comment]
Hmph - the float-right on the 'close' button indicates that the code has changed (this is on `gh-pages`), but no download buttons, indicating that it's using an old (cached?) version of the NR json spec that doesn't have `IndicatorID`. 

![image](https://user-images.githubusercontent.com/55593359/202470043-7ecd3c96-dc90-4461-8ba0-356a494f5fc7.png)

**Comment by mmontesanonyc** [comment]
This is ready to merge to prod, and deploy. Not sure we need to do that this week - since we may wind up troubleshooting some hugo cache / build issues along the way. On ice till after the holiday.

**Comment by mmontesanonyc** [comment]
Interesting - this was merged into prod but (caching issues?) didn't become part of the build when on the recent deploy. Should we build to prod with `--ignoreCache`?

**Comment by cgettings** [comment]
Yeah, let's do that. Just change it in the workflow on a new branch, then merge. Should cover all bases.

**Comment by mmontesanonyc** [comment]
went ahead and merged that in, we can redeploy whenever. Gonna close this too!
