### ISSUE TITLE
Lost highlighting on AQE and HVI

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#212]
We lost the neighborhood highlighting on the map and bar charts in the AQE and HVI.

It looks to me like we are perhaps not passing selectNTA in to the code that builds the spec - 

![image](https://user-images.githubusercontent.com/55593359/196446966-7183d691-3f41-4489-82ec-6cdd393fd6d6.png)

...but when I assign `selectNTA = neighborhoodData[0].GEOCODE`, it still doesn't work... and the script assembling/building the spec and its variables is a bit confusing to me - and storing the spec offsite winds up creating some problems around editing. Wonder if it would be better to re-build these modelled after how the DE works, with the spec as part of the code that executes it.

**Comment by mmontesanonyc** [comment]
Did the following:

- Updated the AQE with more UTD styles; wasn't necessary to do on the HVI.
- Restored map highlighting on both, for the selected neighborhood
- Simplified the JS on the AQE more than a bit, including reducing the required specs, and bringing specs into the site repo instead of storing remotely. 

- [ ] Upon merge to prod, we can delete the HVI and AQE remote specs.  

@cgettings could you please put a second set of eyes on this, at the `hotfix-AQE-HVI-fix` branch? I want to make sure I didn't overlook anything. Thank you!

**Comment by cgettings** [comment]
I think everything looks good. I just made some minor tweaks to some other things.

**Comment by mmontesanonyc** [comment]
Great, thanks. I'm going to merge into `development`.

**Comment by mmontesanonyc** [comment]
This'ns merged into `development` and `production` and is waiting for deployment.
