### ISSUE TITLE
Update NR download data link

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#27]
- [ ] Move button to bottom
- [x] Update to EHDP-data repo
- [ ] Include report-specific or neighborhood-specific filtering?

**Comment by mmontesanonyc** [comment]
I'm working on this, but was briefly confused by the fact that the download button grabs a variable called `data_download_loc` which I could not find referenced or declared in our source code. Momentarily forgot that we are storing the report x neighborhood json spec at [EHDP-data](https://www.github.com/nychealth/EHDP-data). 

The [report x neighborhood json spec](https://github.com/nychealth/EHDP-data/tree/prod/neighborhood-reports/reports) define `data_download_loc`. @cgettings, could you please update and re-export, changing those to the following?
- Active Design: https://raw.githubusercontent.com/nychealth/EHDP-data/prod/neighborhood-reports/data/Active%20Design%20Physical%20Activity%20and%20Health_data.csv
- Asthma: https://raw.githubusercontent.com/nychealth/EHDP-data/prod/neighborhood-reports/data/Asthma%20and%20the%20Environment_data.csv
- Climate: https://raw.githubusercontent.com/nychealth/EHDP-data/prod/neighborhood-reports/data/Climate%20and%20Health_data.csv
- Housing: https://raw.githubusercontent.com/nychealth/EHDP-data/prod/neighborhood-reports/data/Housing%20and%20Health%20_data.csv
- Outdoor Air: https://raw.githubusercontent.com/nychealth/EHDP-data/prod/neighborhood-reports/data/Outdoor%20Air%20and%20Health_data.csv

I'll start by moving the button; when you have a chance to export revised report x neighborhood json, I can add a little JS that ingests the CSV, filters by selected neighborhood, and downloads that as a CSV.

**Comment by cgettings** [comment]
@mmontesanonyc paths changed, and also edited a bit.

**Comment by mmontesanonyc** [comment]
I moved the button, ingested the csv, filtered by neighborhood, and triggered a download. Happy with this.
