### ISSUE TITLE
NR enhancements

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#281]
A few ideas for the NRs:
~~[Link to indicator page in the DE](https://github.com/nychealth/EH-dataportal/issues/193) - this would involve updating the NR json spec with URLs to the current site - or something native using `subtopics-indicators.json`?.~~

Move NR spec to site repo instead of data repo. 

Incorporate a map. I spent a little while getting familiar with Leaflet last week and have a few ideas about how to do this.  This could take a few different forms:
- Clickable map from the NR selection page (related: I'd be interested in revising the NR selection page/landing page, and the output page template, so that they look similar - so that the feeling is that the page gets populated on selection).
- Zoomed in map on the selected neighborhood, on the report output page; with ability to select a new neighborhood on map click.
- Single-pager - a major structural revision where each neighborhood/topic combo loads in an iframe that's part of the overall page; so there's a single page header with the report and map selection (this would have more seamless map-click-selection functionality since that wouldn't load a new page - just a new iframe). This is probably the most sensible approach, but does require a pretty significant rebuild from the ground up - so feels like it's got a higher effort:impact ratio. 

A few rough ideas below, would love your thoughts @cgettings.

![image](https://user-images.githubusercontent.com/55593359/200320697-b7c5b94f-52b3-4b74-bbf2-ccac04eaf8ef.png)

![image](https://user-images.githubusercontent.com/55593359/200320678-5b1b4abc-3a39-450f-80f3-18eb7efebffd.png)

**Comment by cgettings** [comment]
It seems like we don’t necessarily need to use an iframe to change the page content. But it also feels like this might run counter to the idea of a static site. But I still like the idea. 

ETA: linked pages are probably also better for SEO

**Comment by mmontesanonyc** [comment]
Updating with "move spec to site repo."

@cgettings i noticed you also committed adding --ignoreCache to the build - I thought I did that, but, the NRs on prod still don't have the link to the Indicator. Maybe we just need another production build and deployment?

**Comment by cgettings** [comment]
@mmontesanonyc I noticed a problem with the indicator links code, and I fixed it in the dev branch. The download button element IDs are IndicatorIDs, but sometimes the report has different measures from the same indicator, which causes the IDs to clash and the download button to fail. 

I can try to cherry-pick for a hotfix, or just manually make the fix.

**Comment by mmontesanonyc** [comment]
oh interesting. right, because it uses the indicator ID to give a unique element ID to the button. i didn't catch that. yeah, could you cherrypick or manually make that fix? i'd like to get it on the prod queue.

**Comment by mmontesanonyc** [comment]
- [x] Link to DE/indicator from NR

**Comment by mmontesanonyc** [comment]
I'm going to close this issue for now. Links to indicators are working, and we have no imminent plans to revise the NRs with clickable maps. Definitely something we can work on in the future and re-open the issue then.
