### ISSUE TITLE
Move search button from header to nav bar

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#302]

**Comment by cgettings** [comment]
@mmontesanonyc Check this out when you get a chance. It moves the search icon to the nav bar on lg+ screens, and keeps it in the header for everything smaller. The input box also opens below the header for both locations. 

I think it looks and works better like this, but it also will appear on the data stories, where we hide the header.

**Comment by mmontesanonyc** [comment]
Nice. It looks good.

This is the sort of thing that would be good to test with users before deciding whether to make the change, so I'd like to sit on this and consider a testing plan before going to prod. 

I wondered what it would be like if the button in its new position still revealed the search bar in the old location, but generally I think it would be weird to have a button control something _above_ it - that's a sort of unexpected hierarchy of information. Buttons can control things that are more toward the center of the screen, usually not more toward the edge. 

Another thing it could do would be to slide out and reveal the search bar _in place_ of the nav bar - possibly using `.collapse-horizontal` ([doc](https://getbootstrap.com/docs/5.1/components/collapse/#horizontal)). This would be quite a bit of extra fiddling - maybe hitting the search button collapses the nav bar into the hamburger menu and reveals the search bar on the nav bar. Not sure if it'd be worth the extra effort.

**Comment by mmontesanonyc** [comment]
I'm going to close this as inactive right now. It's in the "Data Explorer/Site Enhancements" bit in our project board and document, and I want to keep the Issues list focused on active things.
