### ISSUE TITLE
DE data loading bug on dev, prod

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#309]
Just encountered a recent issue with Asthma data. Clicking through the indicators, there's some inconsistent loading of the data, especially instances where the newly chosen indicator _doesn't_ load, or it does load but it doesn't load the new indicator title and description. 

This is on both `gh-pages` and on `prod-deploy`/live.

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/55593359/202735039-248fc633-2faf-40df-8375-bf0968c526b2.png">

**Comment by cgettings** [comment]
I think this might be an issue that we solved pre-bundling, and which we failed to transfer over. I'll dig into it.

**Comment by mmontesanonyc** [comment]
Yeah, it feels like the same pattern. Might even have an issue for it. Thanks for looking into it!

**Comment by cgettings** [comment]
Another error thrown from `filterSecondaryIndicatorMeasure` 🙄

**Comment by cgettings** [comment]
It's a problem with the data, can be fixed by editing an SQL server view

**Comment by cgettings** [comment]
Fixed after updating data repo
