### ISSUE TITLE
NR bug fixes

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#329]
A collection of NR bugfixes and improvements. 

- [x] NR Chart display (below)
- [x] [NaN is ranked "Better" in NRs]
- [ ] Climate Report: Poverty - only showing 2008-2012.
- [x] Footer is the same for each report, instead of unique for each report. 

Chart display:
![image](https://user-images.githubusercontent.com/12686912/207099473-fdca0fb5-bf0b-49f2-bded-f5f4ea95b4ce.png)

NAN issue:
![image](https://user-images.githubusercontent.com/55593359/208137891-7f867a41-9657-449e-92cc-dbfc4d9599df.png)

**Comment by cgettings** [comment]
Also mouseover behavior

**Comment by cgettings** [comment]
Also poverty is weird
![image](https://user-images.githubusercontent.com/12686912/207101952-31defb42-d0ea-428b-8c30-ecbff437dd0e.png)

**Comment by cgettings** [comment]
Labels are fixed, but we're still displaying single-time trend charts. There's a `trend_flag` field in the report JSON that flags if there's only one time period. We should incorporate this (though as Aaron pointed out, it's not "wrong", just a little dumb).

**Comment by mmontesanonyc** [comment]
Agreed. btw - should we consolidate these 3 NR bugs into a single "NR bugfixes/enhancements" issue?

**Comment by cgettings** [comment]
Yeah, let's do that

**Comment by mmontesanonyc** [comment]
It occurred to me that NAN ranked better might not actually be an issue. NAN is there because the number is small so suppressed, which probably IS better. i think better/middle/worse is based on 1/2/3 values in the data file, rather than direct value comparisons, for this very reason.

**Comment by mmontesanonyc** [comment]
#476 - report footer data was all the same. merging this in to prod.
