### ISSUE TITLE
Add footer column with "report a bug/error"

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#330]

**Comment by mmontesanonyc** [comment]
Are you thinking of this being something on the whole site template, or on the DE?

**Comment by cgettings** [comment]
Just the home page, as a new card in the same row as "About Us"

**Comment by mmontesanonyc** [comment]
Maybe we just modify the Github card to "Report a bug" - focusing on the action not the thing. 

<img width="399" alt="image" src="https://user-images.githubusercontent.com/55593359/208142460-359f9a16-a8f2-403b-a21e-31eeb0bfa07a.png">

**Comment by cgettings** [comment]
Aaron's idea was that this could be a form that sends us an email, so that people who don't use github can send us bugs

**Comment by mmontesanonyc** [comment]
Ah, gotcha.

**Comment by mmontesanonyc** [comment]
I'm going to close this as inactive right now. It's in the "Data Explorer/Site Enhancements" bit in our project board and document, and I want to keep the Issues list focused on active things. 

This is one of those things we can bundle into site template updates to test, like the search btn location too.
