### ISSUE TITLE
NaN is ranked "Better" in NRs

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#337]
![nothing is better](https://user-images.githubusercontent.com/12686912/207502915-2643eb2b-c71d-469c-8aba-e624ca8a0b31.png)

**Comment by mmontesanonyc** [comment]
we should be able to add a condition in there that removes the comparison and says something like "too small to display reliably."

**Comment by mmontesanonyc** [comment]
Closing and consolidating [here](https://github.com/nychealth/EH-dataportal/issues/329).
