### ISSUE TITLE
Realtime AQ not working in this repo...

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#37]
but working in the old 'working' repo. Looking like a CORS issue, might be something to chat through with MP re: azure feeding the site staged here in Github.

**Comment by cgettings** [comment]
@mmontesanonyc I think you're right - I remember something on the Azure end with allowed URLs

**Comment by mmontesanonyc** [comment]
MP's out this week but we can get him on it when he's back.

**Comment by mmontesanonyc** [comment]
MP is lookin' into this.

**Comment by mmontesanonyc** [comment]
MP updated CORS settings, RTAQ functional again.
