### ISSUE TITLE
environment-specific modals

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#39]
re: environment variables, we could just wrap `conditional-modal.html` in an environment variable ([like this](https://discourse.gohugo.io/t/questions-about-hugo-environment-variables/17865/9)) to create environment-specific modals. No need to do that now but it's probably something we should do in the coming month or so.

_Originally posted by @mmontesanonyc in https://github.com/nychealth/EH-dataportal/issues/6#issuecomment-1197212534_

**Comment by mmontesanonyc** [comment]
Staging: revise the title to say "prototype" or similar


```
Welcome to the EH Data Portal prototype
This prototype is a work in progress. That means that not all of the data or information is final. But, feel free to click around and explore.

Please sign up for our email list. We will email you every few months with updates, or opportunities to participate in user research. [Click here to sign up](https://docs.google.com/forms/d/e/1FAIpQLSfUg3JE5ODNc6aqBPJwM8mZ80TYtK6ISw-OM7PBwKuoN3M--g/viewform).
```


Production: 
```
Welcome to the new Environment & Health Data Portal.
The site looks different, but a lot of the content is the same on the old site. We hope we've made it easier to find and understand information on the site. 

Please sign up for our email list. We will email you every few months with updates, or opportunities to participate in user research. [Click here to sign up](https://docs.google.com/forms/d/e/1FAIpQLSfUg3JE5ODNc6aqBPJwM8mZ80TYtK6ISw-OM7PBwKuoN3M--g/viewform).
```

**Comment by mmontesanonyc** [comment]
Hey @cgettings, two FYIs about this - 

I added environment specific code, using `hugo.Environment` and not `getenv` as previous placeholder had it. I tested this by just delivering text onto a page and serving up the different environments, and it's working. Secondly, I also updated the analytics placeholder in `head.html`. 

Going to merge it on in.

**Comment by mmontesanonyc** [comment]
Merged, closing.
