### ISSUE TITLE
Data explorer: data download button

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#4]
Add a data download button on the Data Explorer page that triggers a download of the indicator that's being displayed. A few ideas for this:

**Simple approach**: button triggers formatting of indicator json as CSV and downloads it.

**More detailed approach**: Button triggers two options:
- this view
- full indicator dataset

...and then triggers download of selected CSV.

**Comment by mmontesanonyc** [comment]
Started out with triggering the download of the full indicator.json.

Next up I'll set the Download Data button to trigger a little collapse menu that offers 'This View' and 'Full Indicator' options. It'll take a little bit of digging through CD's code to find the arq table that feeds the current view, though.

**Comment by cgettings** [comment]
Just make sure that the view isn't created using DataTables filtering.

**Comment by mmontesanonyc** [comment]
Moved to [data-explorer-enhancements](https://github.com/nychealth/EH-dataportal/tree/feature-data-explorer-enhancements).
