### ISSUE TITLE
modify URLs where we link to portal

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#42]
E.g., from the housing data story:

`- [Data on childhood asthma emergency department visits](https://a816-dohbesp.nyc.gov/IndicatorPublic/Subtopic.aspx?theme_code=2,3&subtopic_id=11) come from the New York State Statewide Planning and Research Cooperative System (SPARCS) Deidentified Hospital Discharge Data.`

**Comment by mmontesanonyc** [comment]
Going to create a URLfix branch, run a search on the repo, and remove or update these links.

**Comment by mmontesanonyc** [comment]
[Branch here](https://github.com/nychealth/EH-dataportal/tree/hotfix-modify-URLs). I started by pulling off glossary links. Links in data stories will take a little bit more.

**Comment by mmontesanonyc** [comment]
I always forget linking within markdown, but [info is here](https://gohugo.io/content-management/cross-references/).

**Comment by mmontesanonyc** [comment]
All set. 

NB there are a few a816-dohbesp.nyc.gov URLs remaining, but they're to items that can stay (like the CD/UHF comparison tool). Updated all of the links to indicators or data stories.
