### ISSUE TITLE
Enhance disparities functionality

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#455]
Disparities functionality:
- if Disparities flag is on in indicators.json, show a "Show disparities" button on the Links view
- When user clicks button, active state is added, and data are sent to the disparities spec 
- If user selects a different indicator from the Links dropdown list, the Disparities button loses the `active` class, and the Links functions as usual. 

Questions:
- should the function modify the existing spec? Or just draw a revised spec?
- should we remove Poverty from the Links drop-down?
- We may want to add other disparities options (eg, by ICE score). What can we do to plan for a future where the disparities button might be a disparities drop-down? 

Gist for disparities spec is [here](https://gist.githubusercontent.com/mmontesanonyc/a4e54bf377ce778f754226a3635e4750/raw/33fc374721ed6fb360a21729cff9bf40fc4bbeef/spec.json) and prototyped [here](https://github.com/nycehs/Portal-Prototype-Working-Files/blob/master/Data%20Explorer%20viz%20spec/disparities-spec.html). 

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/55593359/214072942-25ac5f02-cec9-41ee-bd83-11986beed047.png">

**Comment by mmontesanonyc** [comment]
Note: recommendations to _not_ include color-by-borough to focus the visualization on the disparity.

**Comment by mmontesanonyc** [comment]
@cgettings, one thing that would be nice to do here is to get the Links and Disparities view to have title font styles that match the map and trend chart. I like the hierarchical nature of the map and trend ones, with the indicator name above the measurement name (displayType?) - mind tweaking styles in those specs?

![image](https://user-images.githubusercontent.com/55593359/234352558-0c797058-71fd-4e6b-b7d2-fcf2fb08b6a8.png)

![image](https://user-images.githubusercontent.com/55593359/234352478-438b7501-4f81-4543-9e26-2397d28e9a5c.png)

**Comment by mmontesanonyc** [comment]
And, an idea for the interaction. Possible to combine the Show Links and Link to menus? This could be expanded if/when we add more Disparities Options, too. I think that would be a little tidier. 

<img width="247" alt="image" src="https://user-images.githubusercontent.com/55593359/234575053-d8743505-d00c-4ead-9974-6c269031a250.png">

**Comment by cgettings** [comment]
@mmontesanonyc I like it

ETA: Though I'm a little worried it'll be confusing in the context of the dropdowns in the other tabs

**Comment by cgettings** [comment]
ICE

**Comment by mmontesanonyc** [comment]
> ICE

- [x] Push existing disparities functionality to prod (worth an announcement to email list)
- [ ] Add ICE indicator 
- [ ] Longer term: revise disparities functionality to offer ICE as an option 

Leaving interaction as-is now but leaving door open for more ideas on interaction pattern - plus, good candidate for usability testing.

CC @etorem
