### ISSUE TITLE
interactive HVI - map data busted

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#46]
Just noticed, and I think this is fairly new:
https://nychealth.github.io/EH-dataportal/key-topics/climatehealth/hvi/

...map is showing all one color, and neighborhood names and values aren't coming through. There's nothing unusual in the console. Haven't done much digging. @cgettings can you look into it please?

**Comment by cgettings** [comment]
I've been busy breaking things, so I'm not surprised.

**Comment by mmontesanonyc** [comment]
This should be solved once data pipeline in #36 +/or geocode standardization in #49 are finished.

**Comment by cgettings** [comment]
Completed by #47
