### ISSUE TITLE
DE enhancements related to DWQ

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#477]
Related to #240 - WM spelled out some specific requests for how DWQ data are displayed.
- **Low hanging fruit**: Default measure display to annual average instead of MCL. This can probably be done with another conditional added to the `renderMeasures()` function that recently saw some changes to rate defaults
- Multiple measures (in progress #190)
- Label axis with quarters
- Limit trend to 3 years (despite inclusion of more data in the table)

This gets at some questions around standard DE app (and its expectation of standard data) versus topic/dataset-specific customizations. I'm not sure of the best approach here, but it's on the list for us to figure out.

**Comment by cgettings** [comment]
These should be pretty easy to integrate into the existing code. We’ll just want to make sure the special conditions section is clear and we’ll documented. Will be easy for it to get muddled and confusing. 

Re: quarters, do you mean {qtr} replacing {yr-qtr}?

**Comment by mmontesanonyc** [comment]
re: quarters, I think WM was talking about these x-axis labels on DBPs. but, let's talk about once M2M is done(ish). re: "default measure" I think turning trend off but Compare On will handle that. 

re: "3-years" that gets at heavily individualized requirements again. Wary of that. 

![image](https://user-images.githubusercontent.com/55593359/217893968-a6946462-2ced-43cd-a7ad-f092ccd41b58.png)

**Comment by mmontesanonyc** [comment]
Adding to #240 and closing till we decide to tackle this.
