### ISSUE TITLE
Revise README

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#48]

**Comment by mmontesanonyc** [comment]
Specifically:
- [x] Branches
- [x] Builds
- [x] Data pipeline
- [x] Frontmatter structure
- [x] Partials 
- [x] Conditional modal & want old site feature
- [x] Environment-specific code (analytics, CM, other?)
- [x] Editing featured datasets
- [x] Image handling (Hugo resizing)
- [x] Generating `IndicatorData/subtopic_indicators.json`
- [x] JS Integrity functionality

**Comment by mmontesanonyc** [comment]
re: environment changes mentioned in #167, I started a branch [revise-readme](https://github.com/nychealth/EH-dataportal/tree/hotfix-revise-readme) to capture some changes.

**Comment by mmontesanonyc** [comment]
Got a start on some more substantive Readme revisions. Debating how much Hugo 101 to include in the readme. I think we should definitely focus on the special things we have - basically, what somebody would need to know to update any part of the site, but without being so specific that we'd have to do really in-depth changes in response to small changes.

So far I've pulled out a bunch of Hugo 101 things, but inserted a placeholder for Special Functions. I'm not entirely sure what will belong here, but it might be things like specifying 'featured datasets' (in the data folder), how we handle images, basics around some central partials (especially the related partial) and maybe some more robust documentation around requirements in DEs, NRs, and anything a little more complex.

**Comment by cgettings** [comment]
- [ ] Add config caching info

**Comment by mmontesanonyc** [comment]
@cgettings, i popped open a new branch for some revisions, `hotfix-update-readme`.  I plan to re-organize image storage today and will add guidelines in the readme, too. I forget the config caching info we talked about a few weeks ago.

**Comment by cgettings** [comment]
`maxAge = 0` to turn off cache
