### ISSUE TITLE
Table sorting with CDTA

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#498]
Some weird grouping thing with the DataTable. Might be time to dig into how that actually works.

![image](https://user-images.githubusercontent.com/12686912/217896267-fc02c068-e8fe-4b41-b722-720cd749c306.png)

**Comment by mmontesanonyc** [comment]
Are there CDTAs _and_ CDs for the same year?

**Comment by cgettings** [comment]
Yeah, but we probably don't need to display both.

**Comment by mmontesanonyc** [comment]
Agreed - I think there's a one or the other decision to be made there. CDs would be most consistent with what we have in the past - I feel like the move to CDTAs might be a bigger decision across many datasets.

**Comment by mmontesanonyc** [comment]
Solved @ #510, thanks @sportsmanam!  (knew there was a screenshot somewhere - it was in the issue, not in the chat!)
