### ISSUE TITLE
Check content for typos

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#502]

**Comment by mmontesanonyc** [comment]
@cgettings did you have a list of typos?

**Comment by cgettings** [comment]
Nope. I found them using that spell checking extension, corrected them, then stashed the changes.

**Comment by mmontesanonyc** [comment]
Gotcha. Is there a way to run that extension on a folder? I noticed it flagging individual typos when I clicked on each content, but don't want to have to click through every .md.

**Comment by cgettings** [comment]
I looked briefly for a way to do it for the folder, but didn't find it. I just clicked through all the content.

**Comment by mmontesanonyc** [comment]
Good find on this extension - really helpful. 

in DE:
- [x] About: "maintain"
- [x] Asthma: "addres"
- [x] Bed bugs: "travelling"
- [x] Carbon monoxide: "landords"
- [x] Falls: "adulst"
- [x] Vectorborne: "diseasesare"

DS:
- [x] Streets - "travelled"
- [x] violence - "disparties" "disinvesment" "
- [x] zappa - "estiamtes"

KT:
- [x] Housing - "longterm"
- [ ]
