### ISSUE TITLE
Reconfigure home page

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#518]
Nav bar and header:
- [x] Add search to nav (right side)
- [x] Remove Home button
- [x] Add link to home on Portal Site Title

Page content, first row:
- [x] Create Featured Content box (2/3 columns) - image, title, description
- [x] Create New Content box (1/3 columns - feed): Top 3 data stories, list of datasets

Page content, second row:
- [x] What Is The Environment? Include links to Key Topics (remove Key Topics card/list)

Page content, third row:
- [x] Cards with static images. Data Stories, Neighborhood Reports (n'hood entry/link?), Data Explorer

Subsequent rows: use extant about content. 

![image](https://user-images.githubusercontent.com/55593359/220444994-beb4c152-7476-4e6c-b5d4-df8abe88726c.png)

---

![image](https://user-images.githubusercontent.com/55593359/220445031-c3a85d3c-0014-4c59-b9ab-9715cd6b7e02.png)

**Comment by mmontesanonyc** [comment]
@cgettings, thanks for the branch. 

Removing home, linking the site title, and the work that Chris did to put the search icon here looks great:

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/55593359/220636117-cb548a79-b2b6-4205-8f45-5b63757daed5.png">

However, we run into a problem on the Data Stories template. On this template, we forego the site banner image, so we don't have a link to home. So, I mimic'ed the Search button's styles on the right side to make a Home logo on the left. This raises a question - should we leave it there in all situations? It takes up so little space. 

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/55593359/220638844-d4791fea-31fc-4de2-8b96-dae7f8b7614a.png">

Also noting Chris's good foresight on keyboard accessibility, using the `sr-only` class on the word "Search". I did the same for "Home." That ensures that screenreader software has something to read. 
<img width="868" alt="image" src="https://user-images.githubusercontent.com/55593359/220639410-cb68ca50-b701-489c-bd0f-e06382f94978.png">

Lastly - in looking at the above, "Key Topics" felt a bit weird nestled in among the other main site sections. I moved it to the front, here - since it's at an intermediate step in the architecture. Thoughts on that? 

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/55593359/220639873-7afa04dd-543b-4d06-ad8c-3fff648393f6.png">

Moving on to home page layout stuff we talked about yesterday...

**Comment by cgettings** [comment]
Putting key topics first mirrors the proposed home page structure, which is good. 

I also think re: home that we should keep the nav bar consistent.

**Comment by mmontesanonyc** [comment]
FYI, renamed the branch `feature-home-page-reorg`.

**Comment by mmontesanonyc** [comment]
So, we didn't talk about this in the meeting y'day, but as I worked on the home page, I felt like there were changes to be made, too, to the Data Explorer landing page. Here's what I've got so far - I think it's a bit tidier. Open to comments on this for sure. 

You'll note that I changed the featured datasets to a bunch of winter-specific things. 

![image](https://user-images.githubusercontent.com/55593359/220761115-d92fe275-e620-4a46-a40f-5f04d986bac7.png)

**Comment by cgettings** [comment]
It's a little spare, but I like the direction it's heading in.

**Comment by mmontesanonyc** [comment]
Hey y'all - more progress on the home page. I think this is in a fairly good place at this point, but y'all may have additional ideas at this point, so feel free to add 'em in here! @cgettings @etorem @sportsmanam.

A few things about management. I set this up so that the data stories feature displays the most recent three, but that the other featured content (on this: realtime, and the 'recently updated datasets') are manually controlled by frontmatter in _index.md. That should make it easy for any of us to revise what goes in here. The current 'recently updated datasets' are just placeholders, since that stuff isn't actually live yet. 

Initially I had thought about a more widely-used 'featured data' function that could read an internal site data yaml file and pipe that info into various locations (see use of the featured-data partial), but, I don't know if I see much utility there. Still an option at some point. 

![image](https://user-images.githubusercontent.com/55593359/220935097-c6dc9876-045e-4e89-9b56-bacd166b31c0.png)

**Comment by cgettings** [comment]
The home button has a gray border. That intentional @mmontesanonyc?

**Comment by etorem** [comment]
I think I would still be curious about the idea of having an About menu button up top on the nav bar under which is nested the Github Repo, Jobs etc. as opposed to separate elements/buttons but open to other thoughts on this as well! Then the e-mail list button can live down there on its own, maybe left-aligned.

**Comment by etorem** [comment]
And do we need the light green borders around the main navigation buttons at all? I wonder how it would look with just text.

**Comment by etorem** [comment]
And thoughts on leaving off the snippets of actual article text for the Data Stories ticker so that we can do without the Read More button for each story (which maybe feels a little distracting since they are all bolded and so close together?) We can also incorporate writing some teaser text for each story with a character limit so that there is no ellipses and no read more and people will hopefully just know to click on the title?

**Comment by mmontesanonyc** [comment]
Good thoughts. re: Home border, I had to fiddle with the css classes to get the right one, but now the home nav item is fixed. I think we do need the light borders - things seem undefined without them.

I'm hesitant to do a multi-level dropdown with extra About links - dropdowns and nesting can get out of control fast. But, I do like the idea of having an About link available basically everywhere. A standard place is in the upper-right of the header. Think this works? 

re: text snippets - I really like that idea. I'll revise this so that the image and title are clickable. @etorem, we can go over what this looks like in practice. basically, we can add what's called a frontmatter variable for each data story's content file. That variable will contain this teaser text, and then we just reference that variable in the page code. 

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/55593359/220956207-02c8bcc9-28d6-47b6-bad7-5f12cdfa8403.png">

**Comment by etorem** [comment]
I think that About us button is good to have. Sounds great about the snippets!

**Comment by cgettings** [comment]
I think the DE grid would look better if the 4 elements had margins between them, and maybe even light borders. 

The topic buttons are still a little unsatisfying. Not really symmetrical or proportional.

**Comment by mmontesanonyc** [comment]
@cgettings, can you create the DE grid you have in mind? 

And, agreed on the buttons. Here, I hardcoded them in so I could keep the names short, and I think this gets us there:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/55593359/221189015-9b9f90a8-13ef-4723-a9d6-09d17428a89c.png">

**Comment by mmontesanonyc** [comment]
Hey y'all, made the changes we talked about y'day and am going to merge to dev.

**Comment by mmontesanonyc** [comment]
^^ nb @etorem - I referenced this issue in the pull request #533, so it adds a link to that PR in this thread. That's helpful - it means I can scan this thread and know that the work has been merged into Dev.

**Comment by mmontesanonyc** [comment]
@cgettings @etorem @sportsmanam:

Changes are on dev: https://nychealth.github.io/EH-dataportal/

...and email's out to CO, MP, WM.

**Comment by mmontesanonyc** [comment]
Well, mobile's terrible, so that's what I need to tackle next:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/55593359/222258032-fb99c5e4-d631-40a3-9226-fcf030ee9304.png">

<img width="670" alt="image" src="https://user-images.githubusercontent.com/55593359/222258114-87b68b82-d420-41d4-b7c8-3a4ea9a2f5f6.png">

**Comment by cgettings** [comment]
Really about compensating for the zoom level. Here's the section cards at 50% on desktop:

![image](https://user-images.githubusercontent.com/12686912/222260674-3ef9ddde-97d5-4115-953d-4beb279c2916.png)

**Comment by cgettings** [comment]
Maybe [this](https://getbootstrap.com/docs/4.0/components/card/#card-columns) can be useful?

**Comment by cgettings** [comment]
@mmontesanonyc check it out on `feature-home-page-reorg`

**Comment by mmontesanonyc** [comment]
The image looks great as does the re-classing of most things. I popped in and did a little bit of tinkering - the dimensions on featured / data stories / updated data weren't quite right so I re-did that and did a lil bit of poking elsewhere but I think we've dialed it in.

![image](https://user-images.githubusercontent.com/55593359/222450736-d3f7e5db-0b12-4964-8ede-2eccb1d483de.png)

**Comment by cgettings** [comment]
@mmontesanonyc I think I got it yesterday. I used cards because they’re equal width, and I added responsive classes so they wrap. Some other stuff too. I feel strongly about the cards, and somewhat strongly about the header size. Not wedded to anything else.

**Comment by mmontesanonyc** [comment]
I'll pop in and take a look. Would love a screenshot from you too since I know our monitor size/resolutions vary.

**Comment by mmontesanonyc** [comment]
Actually n/m on screenshot, I think I can mimic your display just by lowering the zoom on my own, heh. I think this looks great. The only thing I'm doing is to make the "All data >" link on Recently to have nonbreaking spaces, so it doesn't have a cut wrap to the next line.

**Comment by cgettings** [comment]
Will do. The “responsive” mobile view in devtools was really helpful.

**Comment by mmontesanonyc** [comment]
This has been deployed to prod, so I'm going to close the issue.
