### ISSUE TITLE
Content QA

### ISSUE THREAD

**Issue by etorem** [nychealth/EH-dataportal#522]
Hello, I just noticed a couple small editorial inconsistencies and wanted to list them here for addressing: 

- [x] There are two periods in a sentence in the About text on this page: http://gcappbesp307/dev-test/beta/data-explorer/walking-driving-and-cycling/?id=2112#display=summary

- [x] The last heading in this one isn't formatted like the other headings (it's in regular body text).  https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/data-stories/aq-cooking/ 

- [x] There is a repeated sentence in this story: https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/data-stories/localtemp/

"As the climate changes, NYC faces rising average temperatures and heat waves that place New Yorkers at risk. Already more than 100 New Yorkers die each year due to extreme heat. **Even modest cooling can save lives,** and cooling neighborhoods with trees and other vegetation is a critical step we can take to protect people from hot weather. **Even modest cooling can save lives**

- [x] Fix typo in Read Me

Thank you!

**Comment by mmontesanonyc** [comment]
@etorem, let's add to this...

- [x] Fix typo in readme

...so we can tackle the whole issue in one branch.

**Comment by mmontesanonyc** [comment]
[Comment filed in EHDP-data](https://github.com/nychealth/EHDP-data/issues/92) re: a typo in "Recent driving" indicator description, so I'll close this issue.

**Comment by etorem** [comment]
- [x] There is a typo in Block by Block in the 1969 text block. "the" is misspelled.
