### ISSUE TITLE
Troubleshoot changes to realtime AQ app

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#584]

**Comment by mmontesanonyc** [comment]
Hey @cgettings, wondering if you can help me troubleshoot an issue with a new realtime AQ data feed? New data are in the file nyccas_realtime_DEC.csv file (and realtime.js and spec.json are temporarily updated to reference this file rather than to reference the actual live feed:)

<img width="960" alt="image" src="https://user-images.githubusercontent.com/55593359/226396897-4513682e-fd9c-4b1e-bd22-ad1f7fefd1c1.png">

The main problem is that the buttons and charts don't have corresponding colors: click a button and notice the chart highlight the series with the wrong color. It worked before: `getColors()` gets the colors from `monitor_locations.csv` and inserts them into `spec.json`, so I'm not sure why this is out of whack.

The secondary problem is that with DOHMH monitors back online, CH took out the State DEC monitors and just inserted a single "DEC_Avg" value. There's no location for this - but I'm not sure how to reflect this in the code. Current, not-great stand-in is just giving it a location in the rough middle of the city. We could also draw a button in `drawButtons()` (outside of the loop, but there'd also need to be a color in the spec (maybe just appended to the end of the colors array?).  I think that'll be solveable, but am currently stuck on this other color problem above.

**Comment by mmontesanonyc** [comment]
re: the second problem: here's an approach with manually drawing the DEC monitor button instead of including a location for it in monitor_locations.csv. But the problem is that `updateData()` runs `map.setView...` on the selected location, but there's no location for it.

**Comment by mmontesanonyc** [comment]
@chuskey79 This is what we're working with. Two problem: one is that the colors aren't lining up for some reason. Secondly, clicking a button highlights the location both on the chart and on the map - but for 'DEC Average' there's no map location. We can give it a point location (but that's slightly misleading).

**Comment by cgettings** [comment]
to sort the monitor locations:

```
activeMonitors.sort((a, b) => {
    const nameA = a.loc_col.toUpperCase(); // ignore upper and lowercase
    const nameB = b.loc_col.toUpperCase(); // ignore upper and lowercase
    if (nameA < nameB) {
        return -1;
    }
    if (nameA > nameB) {
        return 1;
    }
    
    return 0;
})
```

**Comment by chuskey79** [comment]
Is it possible to not have the DEC avg on the map?

**Comment by mmontesanonyc** [comment]
Trying to figure that out. Agree that having it on the map is suboptimal, but a lot of these components were designed to work together - it might involve rewriting how a lot of these things work together.

**Comment by chuskey79** [comment]
Could we could give it a lat long that's way off the map?

**Comment by mmontesanonyc** [comment]
I think there are some potential workarounds, like adding a conditional to the function that draws the map points, to _not_ draw that one; and to add a conditional statement to the updateData function, so for that ID, won't run the map zoom part of it. I just have to take a bunch of things apart, hopefully not break them too bad, and put them back together.

**Comment by mmontesanonyc** [comment]
@chuskey79 I gave DEC_Avg a lat/long that's off the map, changed the updateData function to have the map just reset the zoom if DEC_Avg is selected, and changed the map functionality to draw the initial bounds based on a set of monitors that excludes DEC_Avg. So, we should be gtg.

**Comment by chuskey79** [comment]
So, are we good to switch the data source?

**Comment by mmontesanonyc** [comment]
Soon. @cgettings is going to deploy the change to production today, and then he'll let you know when you can switch the code. Thanks!

**Comment by mmontesanonyc** [comment]
Opening again... preview on dev: https://nychealth.github.io/EH-dataportal/key-topics/airquality/realtime/. Click Manhattan - IS143 and notice that the chart shows blue; or Queens, or Queens College, and note that their gray and orange is flipped.

Colors are sent to the chart spec from `activeMonitors`, which is also used to `drawButtons()`. When I look at the activeMonitors and colors in the console, they look correct; when I look at the compiled chart spec, the color array is correct. I can't figure out where this inconsistency is coming from.

The code is a little more complex because it was modified to handle a DEC_Avg value, which doesn't get mapped. That value isn't in the data feed (which keeps changing...!) so I wonder if it has something to do with that. idk.  In short - it used to work, data feed changed, it doesn't work anymore. 

@cgettings
