### ISSUE TITLE
Debug disparities logic

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#700]
Disparities charts are not showing up on Citi Bike indicators, which points to a larger problem with the way the logic is coded

**Comment by mmontesanonyc** [comment]
They both have `disparities:0` in `indicators.json` though. Is there something else the matter?

**Comment by cgettings** [comment]
Bikes per station and docks per station both have them as 1

**Comment by mmontesanonyc** [comment]
Whoops, i was looking at the wrong measure!

**Comment by mmontesanonyc** [comment]
Completed with Jan 2024 major site change push.
