### ISSUE TITLE
Address medium severity elements from appscan

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#711]
Issue will be updated as we make our way through the scan info. 

**actionable**
- [x] Add `rel="noopener noreferrer"` to each link with `target="_blank"`
- [x] Remove text email address, display as graphic using `<img>`

**not actionable**
- _Add to each third-party script/link element support to SRI (Subresource Integrity)._  This appears to have flagged Google Translate, which seems like an acceptable risk.
- _Remove SSNs from your website_. These are numeric patterns that are not actually SSNs.
- _Remove credit card numbers from your website._ These are numeric patterns that are not actually CCNs.
- _Remove source code files from your web-server and apply any relevant patches._  These are just node modules.
- _Move sensitive content to an isolated location to exclude it from a web robot search (re: robots.txt)._ No sensitive content is in robots.txt - just content that we don't need google indexing. 
- _Prevent cashing of SSL pages by adding 'Cache-Control: no-store" and "Pragma: no-cache" headers to their responses. "Disable caching on all SSL pages or all pages that contain sensitive data."_ (no pages contain sensitive data.)

**Server configurations**

- [x] Configure your sever to use the "Content-Security-Policy" header with secure policies
  - HTTP response headers: Name: `Content-Security-Policy`, Value: `default-src https: data: 'unsafe-inline' 'unsafe-eval'`
- [x] Configure your server to use the "X-Content-Type-Options" header with "nosniff" value
  - HTTP response headers: Name: `X-Content-Type-Options`, Value: `nosniff`
- [x] Implement the HTTP Strict-Transport-Security policy with a long "max-age"
  - Copied the URL rewrite rule from [here](https://https.cio.gov/hsts/#configuration-for-common-web-servers) exactly. Will need to integrate it into the Web.config on the live server.
- [x] Issue a "404 - Not Found" response status code for a forbidden resource, or remove it completely
  - ~Changed error page for 403 from "403.htm" to "404.htm" **at the server level** (site-level returns 500).~ This still returns a 403 error code, but shows the 404 page, which is... not effective. Seems like this would be a lot of work for literally no gain. I'm going to say we just don't fix this one. We have no sensitive pages to discover.

**Comment by mmontesanonyc** [comment]
@cgettings, when you get a chance, do you mind reviewing the commits on `hotfix-appscan-results`? I think this covers everything we can do from the site side, though I want to chat through some other things - like the appscan flagging things in our dependencies. Wondering if there's anything we can do about that.

**Comment by cgettings** [comment]
Everything uses SSL, and they’re telling us to strictly enforce that, which would imply never allowing anything to be cached, which would be excessive, especially considering that we have no sensitive data. 

We can do all the server stuff. The 404 rec seems like a general thing. IIS returns 404 for non-site folder paths, and we don’t have any restricted content. 

ETA: ok, looks like they say it’s 403 not 404, but the existence of `js` is already revealed by all the scripts we load from it. Same with `css`. The other directories are legitimate, which is why they return 200.

**Comment by mmontesanonyc** [comment]
Great. That's all done within IIS? Could you please add that to your list for this week so I can get this re-scanned next week? These are all only medium severity, but, the more we remove from the scan results, the better shape we are to move fast thru risk acceptance and certification.

**Comment by cgettings** [comment]
My hunch is that the application errors are SRI hash errors. Seems like it’s simply not loading the scripts. I can look into debugging that, or we can stop fingerprinting our own scripts. I’m not sure what they would think about that, but my brief research tells me it’s probably unnecessary.

**Comment by mmontesanonyc** [comment]
Do you mean, the fingerprinting is probably unnecessary? If it works pretty well for everything _but_ the appscan, i'm fine to just ignore that. The category and info in the report is sufficiently vague that I feel like it's telling us, "Something didn't work quite right for our scanning software," but we know it works well for a nonrobot user.

**Comment by cgettings** [comment]
Re: CSP, it looks like a sufficiently secure CSP would be sure to break something (details [here](https://scotthelme.co.uk/content-security-policy-an-introduction/?ref=scotthelme.co.uk)). So depending on what they deem to be "secure policies", we could be forced to refactor the entire site code.

Even more info [here](https://infosec.mozilla.org/guidelines/web_security#content-security-policy) and [here](https://report-uri.com/home/generate).

**Comment by mmontesanonyc** [comment]
Agreed with your notes re 404/403.

Looks like you did some stuff re CSP, but I'm assuming you stopped short of changes that would require refactoring the whole site code? Maybe that progress will be fine and we can RA anything left, especially with "there's no sensitive content."

**Comment by mmontesanonyc** [comment]
nb @cgettings, we may eventually need to apply the same configurations to the production server - able to replicate your work if necessary? feel free to document in an email, or here, or whatever's handy.

**Comment by mmontesanonyc** [comment]
re-requested, closing this out for now.
