### ISSUE TITLE
Links and Disparities title font styles

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#727]
@cgettings, one thing that would be nice to do here is to get the Links and Disparities view to have title font styles that match the map and trend chart. I like the hierarchical nature of the map and trend ones, with the indicator name above the measurement name (displayType?) - mind tweaking styles in those specs?

![image](https://user-images.githubusercontent.com/55593359/234352558-0c797058-71fd-4e6b-b7d2-fcf2fb08b6a8.png)

![image](https://user-images.githubusercontent.com/55593359/234352478-438b7501-4f81-4543-9e26-2397d28e9a5c.png)

_Originally posted by @mmontesanonyc in https://github.com/nychealth/EH-dataportal/issues/455#issuecomment-1522142736_

**Comment by cgettings** [comment]
I remember this issue now... The other charts are using the chart `title`, but these are using the axis `title`. Only the chart `title` allows a differently styled `subtitle`. So the upshot is that both lines on the multi-line axis `title` will be styled the same, which looks weird, and isn't what we want.

**Comment by mmontesanonyc** [comment]
P straightforwad:

<img width="905" alt="image" src="https://github.com/nychealth/EH-dataportal/assets/55593359/0b943fd7-e315-4734-9d9a-bdf85057ad87">
