### ISSUE TITLE
Data Explorer QA

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#78]
A few things . 

**General functionality**
- [x] DE initially loads N/A with just the default ID, but not a default view - needs a view selection to load data
- [x] #83
- [x] Map's bar chart - multiple measures coming through - seen on AQ, Childhood Lead, and likely others

**Specific bugs I noticed**
- [x] Childhood Lead: [links only showing boroughs](http://localhost:1313/EH-dataportal/data-explorer/lead/?id=2216#display=links
)
- [x] Pre-1960 Homes - [data coming into table as Undefined](http://localhost:1313/EH-dataportal/data-explorer/lead/?id=41#display=summary)
- [x] Children under 5 in poverty - [only NTA is coming thru in table](http://localhost:1313/EH-dataportal/data-explorer/lead/?id=2176#display=summary)
- [x] HAA5 - [data coming thru undefined](http://localhost:1313/EH-dataportal/data-explorer/drinking-water-quality/?id=2043#display=summary)
- [x] [pre-1950 homes x poverty](http://localhost:1313/EH-dataportal/data-explorer/lead/?id=16#display=links) - I wonder if this is an issue with a percent x percent Link function - it doesn't seem quite right, and Time is coming into the tooltip.  [update: I don't remember the issue I saw with this, but right now I'm seeing the axes being incorrect - pre-1950 homes should be on the x and outcomes should be on the y. We specify x and y in indicators.json and in general, all health outcomes should be on the y.]
- [x] #82

**Display/spec specifics**
- [x] Table: we'll need to get the DisplayType field into the column headers
- [x] #85
- [x] Links: remove legend (or: enhance to show boros in legend but neighborhoods in the chart)
- [x] Map: update tooltip to have measure name instead of Value
- [x] Links: update tooltip to have indicator names in labels, not just measures
- [x] Links: put y-axis label horizontal (`”axis”: {”labelAngle”: 0}`)
- [x] Trend: disable chart for measures with single year

**Comment by cgettings** [comment]
Re: "indicator names in labels", this looks pretty clunky:

![image](https://user-images.githubusercontent.com/12686912/186944497-78929a43-9472-4af2-99c9-fd7333109926.png)

Need to think of a way of making this easier to look at.

**Comment by mmontesanonyc** [comment]
It is a little clunky. I wonder how much styling control we have over VL tooltips. Time to look into that VL gallery we were poking around in a little while ago. 

Another idea would be to grab the shortname for that field.

**Comment by mmontesanonyc** [comment]
Part of the Vega/Vega-Lite process involves injecting this tooltip css into `<head>`:

```
<style id="vega-tooltip-style">#vg-tooltip-element {
  visibility: hidden;
  padding: 8px;
  position: fixed;
  z-index: 1000;
  font-family: sans-serif;
  font-size: 11px;
  border-radius: 3px;
  box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1);
  /* The default theme is the light theme. */
  background-color: rgba(255, 255, 255, 0.95);
  border: 1px solid #d9d9d9;
  color: black;
}
#vg-tooltip-element.visible {
  visibility: visible;
}
#vg-tooltip-element h2 {
  margin-top: 0;
  margin-bottom: 10px;
  font-size: 13px;
}
#vg-tooltip-element img {
  max-width: 200px;
  max-height: 200px;
}
#vg-tooltip-element table {
  border-spacing: 0;
}
#vg-tooltip-element table tr {
  border: none;
}
#vg-tooltip-element table tr td {
  overflow: hidden;
  text-overflow: ellipsis;
  padding-top: 2px;
  padding-bottom: 2px;
}
#vg-tooltip-element table tr td.key {
  color: #808080;
  max-width: 150px;
  text-align: right;
  padding-right: 4px;
}
#vg-tooltip-element table tr td.value {
  display: block;
  max-width: 300px;
  max-height: 7em;
  text-align: left;
}
#vg-tooltip-element.dark-theme {
  background-color: rgba(32, 32, 32, 0.9);
  border: 1px solid #f5f5f5;
  color: white;
}
#vg-tooltip-element.dark-theme td.key {
  color: #bfbfbf;
}
</style>
```

It looks like [Custom tooltip HTML](https://github.com/vega/vega-tooltip/blob/next/docs/customizing_your_tooltip.md) is supported - first we create a custom tooltip variable:
```
var tooltipOptions = {
  theme: 'custom'
};
```

Then we pass it in to vegaEmbed:
```
vegaEmbed("#vis", spec, {tooltip: tooltipOptions})
  .then(function(result) {
    // result.view contains the Vega view
  })
  .catch(console.error);
```

And, the last step is having the CSS - I think we'd use the CSS above (the default) as a model and develop it from there:

```
#vg-tooltip-element.vg-tooltip.custom-theme {
  color: red;
}
```

**Comment by cgettings** [comment]
Re: tooltip, I think we should decrease the font size, as well as increase the width of the box. For the box width, we should try this: https://stackoverflow.com/a/62853552. Might be as simple as adding those two lines to `head.html` or DE’s `single.html`. The mobile experience might be bad, but I think that’s a thing we have to figure out generally.

**Comment by mmontesanonyc** [comment]
I learned that to figure out the html for a tooltip, you've got to scroll down in developer tools to see where the code is injected into the dom (at the end). It's a little hard to get all of it but this is the html for the tooltip:

```
<div id="vg-tooltip-element" class="vg-tooltip" style="top: 318px; left: 270.0000305175781px">
     <table>
          <tbody>
               <tr>
                    <td class="key">Neighborhood:</td><td class="value">East New York</td></tr>
               <tr>
                    <td class="key">Estimated Annual Rate:</td><td class="value">16.4</td></tr>
          </tbody>
     </table>
</div>
```

On hover, a few more classes are added to the div: `visible` and `light-theme`. 

I was able to add a little bit of CSS that overwrites the default CSS, but this is definitely a sort of hack-y approach. But it's effective, and I think makes the indicator name / measure combination in the Links tooltip a lot more tolerable.

**Comment by cgettings** [comment]
~looks like the birth defects x air quality links are showing up. weird.~

ETA: confused birth outcomes for birth defects

**Comment by cgettings** [comment]
Seen in [drinking water quality](https://nychealth.github.io/EH-dataportal/data-explorer/drinking-water-quality/?id=2207#display=summary)
- [x] Indicator description is N/A when missing (?)
- [ ] Number rounding after pivot

**Comment by mmontesanonyc** [comment]
> ~looks like the birth defects x air quality links are showing up. weird.~
> 
> ETA: confused birth outcomes for birth defects

on AQ? They're listed in the Links for PM2.5. One thing I noticed is that the `label` field is being used for that menu, which doesn't work - we'll need the indicator name, instead, since things like "adults - age adjusted rate" isn't enough. 
<img width="914" alt="image" src="https://user-images.githubusercontent.com/55593359/187907983-5bc8c1e2-e795-41b8-9158-e2a5cbc450fa.png">

**Comment by cgettings** [comment]
Closing this issue, because everything left is covered in other issues.
