### ISSUE TITLE
Bundle JS libraries 

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#79]
Should we use NodeJS bundling instead of fetching from CDNs and using saved resources? Would probably increase performance, would decrease potential (albeit unlikely) security issues, and would make versioning more consistent. Plus we already use Node for grunt.

**Comment by cgettings** [comment]
Would also make developing over unreliable network connections easier

**Comment by mmontesanonyc** [comment]
Per conversation, let's chat this through with CD/BB and see if this makes sense. Seems like [there are a variety of answers on this](https://stackoverflow.com/questions/7445909/bundling-js-files-vs-cdn). It's probably not something we _need_ to do but something that might be nice to understand and learn regardless.

**Comment by cgettings** [comment]
Completed with #287
