### ISSUE TITLE
Table: No change or obvious error when geo x year combo is invalid

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#82]
Didn’t mean to create this issue, but based on the ideas I had, it makes sense to have one. 

Solutions, ordered by increasing effort:

- [x] Check for 0-length data after filter in summary.js, then show ~error message~ blank table
- [ ]  Default to the nearest valid selection
- [x] Change the drop downs dynamically, to gray out unavailable geo/year based on current year/geo selection

**Comment by mmontesanonyc** [comment]
Error handling of Asthma ED Visits (adults) - /asthma/?id=2380

- What if rebuild geography drop-down when year is selected?
- Show all geographies in geo dropdown, but gray them out if they're not available for the selected year.

**Comment by mmontesanonyc** [comment]
Nice job with the inactive states on this one - I think it looks and works really well. OK to close?

![image](https://user-images.githubusercontent.com/55593359/192530635-8640c994-89e0-4273-bd80-48ccddf781f0.png)

**Comment by cgettings** [comment]
Good to close.
