### ISSUE TITLE
AQ and Drinking Water Quality - handling seasonal/annual average combination in Trend charts

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#83]

**Comment by mmontesanonyc** [comment]
Disinfection Byproducts: want to set default trend measure (via order in data file)

Air Quality: for Neighborhood Air Quality, Black Carbon, PM2.5, NO, and NO2 should show annual averages only in trend data. Currently, it shows both seasonal averages and annual averages. 

edit:
For Air Quality > Neighborhood Air Quality > Black Carbon; PM2.5, NO, and NO2. In the trend display, we see both annual averages and seasonal averages. They should only show annual averages. (This change should only affect these indicators, since SO and O3 should show seasonal averages only.)

**Comment by mmontesanonyc** [comment]
I reviewed what you integrated and merged into staging, and everything looks great. Is there anything else on this that you have in progress or are we good to close?

**Comment by cgettings** [comment]
I think this should be set. Any other edge cases we discover we can just add as a hotfix.
