### ISSUE TITLE
Enhance search with PageFind

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#846]
On `feature-pagefind-search` ([here](https://github.com/nychealth/EH-dataportal/tree/feature-pagefind-search)), enhance search with the following:

**Neighborhood reports indexing:**
- Prevent output pages (eg, a neighborhood-x-report combination, like [this](https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/neighborhood-reports/east_flatbush_flatbush/asthma_and_the_environment/) from appearing as results for health terms (eg, "Asthma"). Instead, have health terms show NR topic landing pages (eg [this](https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/neighborhood-reports/asthma/)).
- For output pages, index so that searching for neighborhood names will return the  neighborhood-specific output pages.
- Can this be done just by using PF's ["limit what can be indexed" docs](https://pagefind.app/docs/indexing)?

**Data Explorer indexing:** Return links to individual indicators in the search results. EG, searching the current site/search for "deficiencies" returns "Homes with 3+ maintenance deficiencies" (an indicator).
- Index a data explorer topic page's indicators and their indicator descriptions - add them to page, hidden, and add indexing tags. (@cgettings can create this index).

**Consider search interaction/design** - especially, searching in modal.

@AdamChlan, please let me know if anything is unclear; + we talked about you tackling the NR tagging first while Chris works on the DE indicator/description index.

**Comment by cgettings** [comment]
Add indicator names and descriptions as attr, then use `data-pagefind-index-attrs` to add to index
Add indicator URL as `url` metadata key, then use `data-pagefind-meta` to add to index as metadata

**Comment by cgettings** [comment]
I'm not sure how to make this work. Doing this with `grunt`/`lunr` was relatively simple because `gruntfile.js` was just manually adding entries to the index. So we could just say "for a data explorer page, add an entry for each listed IndicatorID". Because pagefind automatically indexes pages from the built site, we have to figure out how to get pagefind to turn 1 built page into multiple entries in the index. I haven't found anything in the docs suggesting that's possible, so my hunch is that it isn't (at least without some serious hacking). But I'll keep digging.

**Comment by mmontesanonyc** [comment]
Hmmmm. Before serious hacking, why don't you email Cloudcannon support and see what they have to say about it?

**Comment by bglw** [comment]
Lurking here — I’m releasing Pagefind 1.0 next week, which includes two different features that would both achieve what you need (hack-free!)

@cgettings If you’re still needing a solution let me know and I can point you in a direction.

**Comment by mmontesanonyc** [comment]
Thanks @bglw! Once we take a look at 1.0 I'm sure we'll be in touch - appreciate your responsiveness!

**Comment by AdamChlan** [comment]
@bglw Please let me know if there is a better channel to send this question to, but I figured since you are hooked into this thread it might be a good place to start. 

We are curious about the best path for helping guide PageFind which results should take priority on certain searches. Here is the desired outcome in very general terms:

1. There are certain pages we would like to exclude from results, if a specific search term is searched upon. But we don't want to exclude them from search altogether.
2. There are certain pages we would like to prioritize as top results when specific search terms are searched on.

Can you provide any guidance if this is possible with PageFind, or may be possible in the future? Thank you!

**Comment by bglw** [comment]
Hey @AdamChlan 

Well this is fortuitous! Pagefind 1.0 launched ten minutes ago! https://github.com/CloudCannon/pagefind/releases/tag/v1.0.0

And, it includes content weighting, that should nail what you're after: https://pagefind.app/docs/weighting/

Let me know if that works for you!

**Comment by bglw** [comment]
(Plus the [multiple results per page](https://pagefind.app/docs/sub-results/) mentioned earlier)

**Comment by mmontesanonyc** [comment]
@cgettings and @AdamChlan - I thiiiink this gets us the functionality we need, but it would be great if you two could confirm - we have a meeting on Wednesday and it would be great to use that to figure out any last pieces we need to put in place to implement PageFind. Thanks!

**Comment by mmontesanonyc** [comment]
via @etorem :
- Could we have the site sections in larger and bolder font on the left?
- Maybe we could have the site sections visible when you open the search modal so it's not a giant blank box.
- I'm curious how the titles are weighted in the search (I notice they are not highlighted the way that body text is). When I search air quality, for example, the RTAQ didn't come up till the eighth search result. I assume in practicality we might want this to rank higher up if there's a way we can control that. 
- When I search climate and health, two results called climate and health (title) come up, one of which is the NR. Maybe we'd want to change the "Climate and health" title on the md file to say "Neighborhood Report: Climate and Health" or something so that when people search for it it's clear that the Key Topic and the NR are two different pieces of content. 
- Perhaps a simpler solution to this would be to include some text in Pagefind that indicates which category from the left is being shown on the right instead of having to go in and change all the metadata. Each search result could then be tagged as belonging to a site category. 
- Maybe a more complicated thing to address (and this isn't specific to Pagefind) but if you search a specific neighborhood you only get neighborhood reports and direct text mentions. Maybe we can add a pop-up message or something that encourages people to visit Data Explorer to look at different geographies and they will most certainly find data on their neighborhood, CD, UH42 etc -- I think this might be helpful to remind the average user who might go right to the magnifying glass on the homepage, search a specific neigborhood, and think "oh well there is nothing for my neighborhood here" just because it doesn't come up in DE search results.

---

Thanks - good thoughts. Great catch on the content-related things, around page titles - feel free to make those changes in that branch. re: display stuff, I'm not sure if we can easily make changes to PageFind's UI. 

@cgettings , can you weigh in on Emily's question re: indexing? And, as you're working on indexing indicator stuff, holler if any other indexing ideas come up. 

One thing re: searching specific neighborhoods - might be good to put in the page metadata some additional terms - eg, "Bed-stuy" for Bedford Stuyvesant, plus its constituent ZIP codes - to increase the number of things that PageFind can match on. And, related to this - as one aspect of improving search may happen on the content/metadata end - Emily, could you take a look at the Search Results report in Google Analytics, see popular searches, and make a plan for how we can return the most relevant content?

**Comment by cgettings** [comment]
@etorem We can definitely do 1. We can probably figure out how to style anything any way we want. 2 & 3 feel possible, but we’ll have to look into it. @mmontesanonyc interesting re: additional neighborhood names. We can add hidden elements for stuff like that.

**Comment by cgettings** [comment]
@mmontesanonyc @etorem I think indexing is in a good place. I got the indicators working well, and I've been fooling around with neighborhood reports. A search for asthma will show 1 NR, but a search for a neighborhood will show 6 (5 report landing pages + 1 neighborhood landing page). I still have to add indicator info for the NRs, so that searching "asthma" will show reports with asthma indicators, but that shouldn't be too hard now that I have the data explorer figured out. 

Check it out!

**Comment by mmontesanonyc** [comment]
Really liking how this plays out! Thanks for indexing, Chris.

<img width="1131" alt="image" src="https://github.com/nychealth/EH-dataportal/assets/55593359/60f2460e-5332-4639-b229-a9303c2d8668">

A few things on the list:

- [x] Integration with GA - @cgettings will reach out to PageFind's authors either here or via email for input; please keep Adam in the loop
- [x] Ongoing testing, and refining search results via content - @etorem, it would be good for both of us to familiarize ourselves with ways we can tag specific HTML elements to either appear or not show up in the search indexing (Chris, can you point us in the right direction or write up a summary?), but I'd like you to take the lead on reviewing results and making sure that what we want to show up shows up. One tool for that would be reviewing search terms in google analytics.

**Comment by cgettings** [comment]
Added NR indicator names and descriptions to the topic landing pages. Looking good so far.

**Comment by mmontesanonyc** [comment]
NB: a lot of our site-search terms are for neighborhoods - neighborhood names, including ZIP Codes. Search should absolutely return useful results for neighborhood names, ZIPs, etc. 

- [ ] Write readme/documentation covering tags to use, weighting standards, links to useful documentation (eg HX -> weight equivalence)
- [ ] Revise Key Topic title weighting
- [ ] Ensure good data-features weighting 
- [ ] Add ZIPs to NR weighting 
- [ ] "Get data for TITLE about NEIGHBORHOOD" on `data-explorer/single.html` or `section.html` with low weight so that a neighborhood search turns up Data Explorer opportunities.

CC @cgettings

**Comment by mmontesanonyc** [comment]
Closing this comment and moving enhancement notes to #992
