### ISSUE TITLE
Map: incorporate gray baselayer

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#85]

**Comment by mmontesanonyc** [comment]
[Here's an example of a VL map spec with a gray baselayer](https://github.com/nychealth/covid-maps/blob/main/main/mapRate.vl.json).

Incorporating this as a layer prior to the data layers probably likely involves editing instances when information is sent to the map spec. 

![image](https://user-images.githubusercontent.com/55593359/187723242-18216914-bd94-42f7-9617-f61497716364.png)

**Comment by mmontesanonyc** [comment]
Our spec has:
```
vconcat: [
     {MAP},
     {BAR}
]
```

I wonder if what would work is:
```
vconcat: [
     {"layer": [
          {GRAY-BASE-LAYER},
          {MAP}
     ]},
     {BAR}
]
```

I prepped that [here](https://gist.github.com/mmontesanonyc/93d0fc6fd9757ae3efb794181b9c1960). I feel like it should work, but doesn't...

**Comment by cgettings** [comment]
What do you mean exactly by "it doesn't work"?

**Comment by mmontesanonyc** [comment]
The map renders as before, but the gray baselayer doesn't. Which is a little bit weird - I expected to break the spec, not just to have no change. This includes stopping and restarting the serve, so it's not just Hugo not rendering a change.
