### ISSUE TITLE
Use `flexdatalist` for NR neighborhood search

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#854]

**Comment by mmontesanonyc** [comment]
@cgettings @etorem 

Hey folks - `feature-clickable-uhf` has some NR work I've done. This started from a desire to incorporate a clickable selection map (as a step twoard adding a flexdatalist selection) and just sort of... progressed. There's a lot more I'd like to do in here, but wanted to share basic direction for some collective brainstorming.

Check out the NR landing page, click to a neighborhood, and click to a report. I'd like to refine each page in a few ways:
- The path of landing page -> Neighb page -> output page should look and feel more similar to each other. 
- NR landing page should give some sort of content preview, like other landing pages on our site. It should also have a `flexdatalist` ZIP search
- The Neighb page needs a lot of work, I don't like this layout at all. Could also incorporate some basic info about each neighborhood, if we want to add that content. 

No urgency on this but I'd love thoughts and conversation on this. Might wind up kicking this can down a road for some input from our partners.

**Comment by mmontesanonyc** [comment]
Did a bunch more work bringing the templates and interaction into a place I feel good about.

On an NR output page, clicking the map to a new neighborhood brings you to the neighborhood page, not a NR output page - one of the partials needs to be modified to read the end of the URL and append that to the destination.

I like this more than what we have now, but also open to more thoughts on improvements.

Can/should also incorporate a ZIP/flexdatalist search for the NR Landing Page, as an option below the map.

**Comment by etorem** [comment]
<img width="279" alt="Screenshot 2023-10-27 at 1 44 59 PM" src="https://github.com/nychealth/EH-dataportal/assets/125383655/7cfc1035-6282-44d1-a24b-8055fea1e794">

I like the map, I think it's a fun way to help people select their neighborhood. I removed the border (in inspector) as an option. What do you think? I'll look at it more in-depth as well and leave more comments.

**Comment by mmontesanonyc** [comment]
@etorem which page is that on? the output page, or the interim neighborhood-only page? I've gone back and forth on the border - sometimes it feels like the map needs something to anchor it. 

I've added a few more interaction components to the NR landing page - wondering if these are intuitive? (a user can use the neighborhood-entry box, OR click on the map; there's also a "show neighborhoods" button that shows the full list, and those go to the interim neighborhood-only pages)

Might be worth it to test this with users - once we get thru our current UX stuff.

**Comment by mmontesanonyc** [comment]
nb: using `parts.length` will results in errors when we change the URL's structure (and folder depth). (in `nr-map-highlight.html`). Specifically, due to `window.location.href.split('/')`.

**Comment by mmontesanonyc** [comment]
fyi i put this on dev - going to throw it around to some folks and see if there's anything fixable before moving it on to prod.

**Comment by mmontesanonyc** [comment]
> nb: using `parts.length` will results in errors when we change the URL's structure (and folder depth). (in `nr-map-highlight.html`). Specifically, due to `window.location.href.split('/')`.

this is solved, btw.
