### ISSUE TITLE
Use `flexdatalist` for AQE neighborhood search

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#855]
Which, incidentally, requires a total rewrite

**Comment by mmontesanonyc** [comment]
I've been doing a little bit of thinking on some of our data features, and i've got some additional ideas for improving AQE, including:
- clickable map selection using VL
- loading blank content on the page, and having neighborhood selection populate data (like on the iHVI)
- Some other changes to interaction patterns and layouts that are tbd

**Comment by mmontesanonyc** [comment]
Adding this to my list, and working on it on `feature-rebuild-aqe`. A few notes:
- Requested updated data, at NTA2020, from CH/AQ team.
- AQ team may provide additional content input (like inclusion of charbroilers?)

Rebuild plans:
- Loading whole page with neighborhood-agnostic content, populated on neighborhood selection
- Revising layout to accommodate the above more nicely
- Using `flexdatalist` to drive neighborhood selection

**Comment by mmontesanonyc** [comment]
Done and deployed :)
