### ISSUE TITLE
Table: horizontal scrolling issue

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#87]
On Drinking Water Quality: TTHMs, the table is wide enough to require horizontal scrolling. When horizontal scrolling, the table body scrolls but the header does not. This is a problem.

**Comment by cgettings** [comment]
Header alignment is still wonky:

![image](https://user-images.githubusercontent.com/12686912/187819509-cb43035c-96d1-422f-a841-4def47a6da74.png)

**Comment by mmontesanonyc** [comment]
Finding header alignment issues on a few other areas, too:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/55593359/187903552-a4d04a6c-1731-4acf-82fb-788b98966d04.png">

<img width="721" alt="image" src="https://user-images.githubusercontent.com/55593359/187903650-36615b81-beda-47b4-a033-c36fc1599983.png">
