### ISSUE TITLE
Make sure Vega-Lite `null`s aren't converted to 0's

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#965]
coercing `null` to numeric -> 0, which is very unfortunate behavior 👎

**Comment by cgettings** [comment]
Problem will pop up anywhere there's a pivot

- [x] Trend/comparisons
- [ ] Map
- [ ] Links

**Comment by mmontesanonyc** [comment]
Completed with Jan 2024 major site change push. #963
