### ISSUE TITLE
Access to raw data

### ISSUE THREAD

**Issue by thac2j** [nychealth/EH-dataportal#985]
No file gives access to the raw data for NYCCAS or pathway to a separate repository.

**Comment by mmontesanonyc** [comment]
Hi thanks for inquiring. We do not publish raw NYCCAS monitor data. These data are inputs to an process that uses data on land use, traffic, building emissions and other neighborhood factors around the monitors to build a land-use regression. We  use the associations from these models to estimate the seasonal average air pollution levels at locations across the city, including places where no NYCCAS measurements were collected. This process provides a greater level of utility and reliability than just the raw data. 

You can, however, [email the NYCCAS team directly](mailto:nyccas@health.nyc.gov) to discuss using the raw data. In the meantime, the below data are available for you to use:
- [Neighborhood-level data](https://a816-dohbesp.nyc.gov/IndicatorPublic/data-explorer/air-quality/?id=92#display=summary)
- [Citywide raster maps](https://data.cityofnewyork.us/Environment/NYCCAS-Air-Pollution-Rasters/q68s-8qxv)
- [Raw data for realtime PM2.5 monitors](https://a816-dohbesp.nyc.gov/IndicatorPublic/key-topics/airquality/realtime/)
