### ISSUE TITLE
Implement bubble map for counts

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#997]
re #534, modify `map.js` so that it maps a bubble map spec for non-rate/non-percent measurement types.
- [geoLookup.json](https://github.com/nychealth/EHDP-data/blob/production/geography/GeoLookup.json) includes Lat/Longs for all of our geographies
- Is already joined to the data in `data.js`

**Comment by mmontesanonyc** [comment]
Bubble map is working. A few notes:

First, in the mapspec, in `vconcat[0]`, I added another layer; this is the neighborhood layer, in a gray - this ensures that we get neighborhood boundaries (previous gray base layer was just boroughs). This can stay for both Count and Rap maps (bubble and choro).

<img width="848" alt="image" src="https://github.com/nychealth/EH-dataportal/assets/55593359/4d8ff07f-2acd-491f-80a2-af9b0d76321e">

Secondly, I added some variability to `strokeWidth` - it was a little small on the bubles, so it's 2 on the bubbles and 1.25 on the choro.

**Bubbles are BOTH scaled, and colored** per the data. Is this too much? We can remove the color. But, it helps match it to the bars without additional code. 

NTA maps get a little busy; see CitBike stations for an example, which also shows how null data are handled. 

<img width="848" alt="image" src="https://github.com/nychealth/EH-dataportal/assets/55593359/a67b4fa4-86fd-4c3f-90a6-9e572b9fb06c">

With the blues in rankReverse (and likely with the reds too) we have some contrast issues against the gray basemap, which might call for a stroke on the bubbles. 

<img width="848" alt="image" src="https://github.com/nychealth/EH-dataportal/assets/55593359/2ab5a9aa-1b6d-4789-aa58-a1311c66846c">

@cgettings @etorem thoughts welcome - on `feature-map-count-points`

**Comment by mmontesanonyc** [comment]
I've done a little contrast tweaking. A few specific questions re finalization:
- @cgettings - I put a neighborhood map on top of the boro map to give us a baselayer for bubble view that shows neighborhood boundaries; did you originally use a boro topojson just to use a smaller file for the gray basemap? We could enhance the code to only show the neighborhood basemap on bubble view, or leave both in, or leave only neighborhoods in. What's your preference?
- How are the contrasts looking?
- Right now, the data values are encoded both as size and as color. Is this apparent, or confusing? Keeping the color encoding allows us to match the bar chart (which also encodes values both as size and color) and keep the same legend. 
- We don't have a legend on bubble size, but I think that the tooltip, mutual highlighting, and legend on the color encoding does the needful, here. Open to disagreement, however. Thoughts? @etorem

**Comment by mmontesanonyc** [comment]
Issues: combined color/size legend is preferable, but only works this way if the vconcat'ed bar chart is removed:

<img width="581" alt="image" src="https://github.com/nychealth/EH-dataportal/assets/55593359/06cceebf-9b6a-4dbb-8751-95503ab1fcc4">

A split legend is tolerable, but the values are in opposing orders, and that is unacceptable. 
<img width="581" alt="image" src="https://github.com/nychealth/EH-dataportal/assets/55593359/33d5c7b5-6aa0-4823-b5f4-ae866f1a21eb">

**Comment by mmontesanonyc** [comment]
NB:
- combined bubble/color legend was working on a single map but not working when `vconcat` added the bar chart.
- went into the Vega spec for the working legend, and pulled that into the Vega-Lite spec
- used `"legend": {"disable": true}` in the `config` to remove all legends by default
- used the Vega legend code in the VL spec. 

<img width="824" alt="image" src="https://github.com/nychealth/EH-dataportal/assets/55593359/7e271289-90a3-48d5-93d4-bdab6ca4612d">

**Comment by etorem** [comment]
So for the scale + color does that mean that each bubble has a distinctive shade in the gradient and matches the bars exactly?

**Comment by mmontesanonyc** [comment]
> So for the scale + color does that mean that each bubble has a distinctive shade in the gradient and matches the bars exactly?

Yup. There may be sliiiiight differences because the bubbles are partly opaque (to help manage overlap - along with having a stroke around them), but they are encoded with color along the same scale/range as the bars.
